### PR TITLE
Move templates validation in app.ready

### LINKED ISSUE #4945: deadlock at load time from register_plugin
In plugin_pool.register_plugin, which runs at load time, plugins are validated in part by loading their templates.  Third party django apps can provide template loaders that can reference models.  Since django 1.7, that's not allowed.  In my case, this is causing deadlock through a nested call to django.apps.apps.populate().  Further discussion here:

https://groups.google.com/forum/#!topic/django-users/WiRzQ8EFOdo
https://groups.google.com/forum/#!topic/django-developers/YvEzdQU4qUU
https://groups.google.com/forum/#!topic/django-cms-developers/CNWHNviqS6Q

I suggest, in the latter thread, to separate plugin registration and validation and do the latter in cms.apps.CMSConfig.ready().  I'm willing to create a pull request if you agree with this in principal.

John

### PR DESCRIPTION
**Pull request by yakky**
Fix #4945

### CODE REVIEW

**Comment by yakky** [comment]
Test failures due to #4948

**Comment by yakky** [comment]
Synced with upstream to let tests pass

**Comment by yakky** [comment]
@mkoistinen @czpython ready for review

**Comment by mkoistinen** [comment]
I'm pleased with this. I also love the attention you paid to formatting/cleaning things up.

**Comment by yakky** [comment]
It's my near year's resolution: progressively clean up the cms code style

**Pull request merged**
