### PR TITLE
Update docs: `djangocms_picture` to `cms` folder

### PR DESCRIPTION
**Pull request by adrienbrunet**

### CODE REVIEW

**Comment by FinalAngel** [comment]
LGTM

**Comment by adrienbrunet** [comment]
:metal: With a one word change, I'm about to become a contributor to django-cms, *drumrooolll* yeaaaaah. Keep rocking

**Comment by FinalAngel** [comment]
@adrienbrunet that's all it takes, one fix at a time :)

**Comment by evildmp** [comment]
@adrienbrunet Be warned, that's how it starts.

**Pull request merged**
