### PR TITLE
[WIP] Hide plugins

### PR DESCRIPTION
**Pull request by nmashton**
This is implementation of the feature described in issue #4512, trying to follow the implementation suggestion given by [this comment](https://github.com/divio/django-cms/issues/4512#issuecomment-143528095) (after a false start with making the field editable). Feedback is requested!

To hide a plugin, just choose the "Hide" option in its dropdown menu. The plugin and all aliases dependent on the plugin will be hidden. (The menu item will also become "Show".)

One question for the core developers: *should* all the aliases depending on a hidden plugin be hidden? My client has a use case for which this makes sense (hiding seasonal content); but is that going to the most common situation?

One minor incomplete feature of this branch: a class `cmsplugin-hidden` is added to the `cms-dragitem` element if the plugin's `cmsplugin_hidden` value is `True`, but this added class currently does nothing. What would be an intuitive way to indicate the "hidden" status of the plugin?

### CODE REVIEW

**Comment by czpython** [comment]
Hello @nmashton,
Thank you for taking on this task.

I have some reservations regarding the feature itself, we have not discussed it thoroughly with the rest of the core developers or the board. As such, we'll discuss it on our next board meeting (Monday next week).

Just to be clear my reservations are regarding the following:

- Will this be used enough to balance with the extra code added to the core?
- Is it possible to make it into a separate app?
- Can we avoid adding a new field to the `CMSPlugin` class?
- Design-wise we need to come up with something to show that this plugin is hidden.

**Comment by yakky** [comment]
I don't see why you can' implement this with a wrapper plugin where you can implement complex policies to show / hide content instead of a simple boolean

**Comment by nmashton** [comment]
@yakky: thanks for the suggestion; I will take a look at aldryn-segmentation (etc) for inspiration and attempt an implementation along those lines.

@czpython: great, thank you. I look forward to hearing the outcome of that discussion.

**Comment by czpython** [comment]
Hello @nmashton,

As promised, here's the outcome of the board meeting in regards to this feature:

The consensus is that this is good feature to have at the plugin level (vs nesting plugins).
That said, we think that adding this to the core is not ideal as it would cause several issues with existing plugins due to migrations, as well as the fact that we're trying to simplify the core as much as possible and strip it from features that can be done in third party apps (ie. revision history).

We'd like to help with the design of this app (if you're ok with it).

Here's our suggestions:

* Create a new model with a relationship to `CMSPlugin` class.
* Add a `disabled = BooleanField(default=False)` field to this class.
* Create a plugin on this app whose only purpose is to extend the global plugin menu actions, this plugin is not renderable or even shown to the user, it's only used internally. I'm not too fond of this approach (abusing plugin to extend menu only) but I think it's the easiest solution for now, anything else would require a big change on the core to allow non plugins to extend the plugin actions menu. The [alias plugin](https://github.com/divio/django-cms/blob/release/3.4.x/cms/cms_plugins.py#L62) is a good example of how to achieve this.
* An advantage of using an internal plugin is that you can use the `get_plugin_urls()` method to register the ajax endpoint that will be called when a user activates/deactivates a plugin.
* Naming-wise, we suggest "disable" and "enable" as the action names, "hide" and "show" are used by the structure board already and this can confuse some users.

I think that should cover most of the logic/design of the app, the main things missing are:

* Somehow get the cms to know about the disabled field and not render the plugin.
* Performance impact per plugin

I can help extending the cms to tackle those two, just need to figure out what is best generic approach.

If you're still interested, please create a topic in the [django CMS developers group](https://groups.google.com/forum/#!forum/django-cms-developers), we can continue our collaboration there.

**Pull request closed without merging**
