### PR TITLE
Removed revision support from core

### PR DESCRIPTION
**Pull request by czpython**
As announced, we're removing revision support from the core and will re-introduce it as a separate app.

The _History_ menu entry is gone along with the _Undo_ / _Redo_ / _Revert to live_ options.

@divio/django-cms-core

### CODE REVIEW

**Comment by czpython** [comment]
Ping @yakky

**Comment by yakky** [comment]
@czpython LGTM

**Comment by fuzzy76** [comment]
Where was this announced? I can't find the rationale anywhere, and I am quite frankly a bit puzzled by anyone shipping a CMS without revision support since it is normally regarded a pretty basic functionality.

**Comment by bharling** [comment]
Blimey, yeah this one caught me out too, wasn't aware it was to be deprecated. Do we have an alternative available yet?

**Pull request merged**
