### PR TITLE
Fix #3674

### LINKED ISSUE #3674: Unable to delete page after related template was removed
After I had removed template landing.html, I've tried to delete the related pages.
In result, I'm getting such ridiculous error:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/twiket/local/lib/python2.7/site-packages/mptt/models.py", line 864, in delete
    super(MPTTModel, self).delete(*args, **kwargs)
  File "/home/twiket/local/lib/python2.7/site-packages/django/db/models/base.py", line 695, in delete
    collector.delete()
  File "/home/twiket/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 255, in delete
    sender=model, instance=obj, using=self.using
  File "/home/twiket/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/twiket/local/lib/python2.7/site-packages/cms/signals/title.py", line 93, in pre_delete_title
    instance.page.save(no_signals=True)
  File "/home/twiket/local/lib/python2.7/site-packages/cms/models/pagemodel.py", line 455, in save
    self.save_base(**kwargs)
  File "/home/twiket/local/lib/python2.7/site-packages/cms/models/pagemodel.py", line 475, in save_base
    ret = super(Page, self).save_base(*args, **kwargs)
  File "/home/twiket/local/lib/python2.7/site-packages/django/db/models/base.py", line 582, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/twiket/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/twiket/local/lib/python2.7/site-packages/cms/signals/page.py", line 24, in post_save_page
    instance.rescan_placeholders()
  File "/home/twiket/local/lib/python2.7/site-packages/cms/models/pagemodel.py", line 1218, in rescan_placeholders
    placeholders = get_placeholders(self.get_template())
  File "/home/twiket/local/lib/python2.7/site-packages/cms/utils/plugins.py", line 150, in get_placeholders
    compiled_template = get_template(template)
  File "/home/twiket/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/twiket/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: landing.html
```

It must be possible to delete a page after template deletion!

### PR DESCRIPTION
**Pull request by yakky**
Fix for #3674 allowing deletion of pages attached to non existing templates

### CODE REVIEW

**Comment by yakky** [comment]
@mkoistinen @ojii does disconnecting signals on page delete makes sense in your opinion?

**Comment by mkoistinen** [comment]
I worry that taking this approach of disconnecting signals is going to set the wrong precedent. Is it possible to instead pass in a flag "force_delete=True" or something that can be carried into the logic and allow us to make the right decisions in the right contexts?

**Comment by ojii** [comment]
disconnecting signals feels wrong. agree with @mkoistinen this should be handled differently.

if there's no way around signal disconnect, at least wrap it in a contextmanager or try/finally

**Comment by yakky** [comment]
@mkoistinen @ojii I agree with you
This is just a tentative work to explore different solutions

**Comment by yakky** [comment]
Moving to 3.1 anyway

**Comment by ojii** [comment]
sounds good

**Comment by yakky** [comment]
@ojii @mkoistinen does it sound correct to you to ignore TemplateDoesNotExist at https://github.com/divio/django-cms/blob/develop/cms/signals/page.py#L24
In post save it's anyway too late to take action so swallowing the exception does not really change the ability to interrupt the wrong change

**Comment by yakky** [comment]
The linked PR is an alternative approach with mutes the exeception in ``post_save_page``

**Comment by yakky** [comment]
Closing in favor of #3935

**Pull request closed without merging**
