### PR TITLE
Release 3.6.0

### PR DESCRIPTION
**Pull request by vThaian**
Back port #6604

### CODE REVIEW

**Comment by jrief** [comment]
Please remember to merge #6457, otherwise some icons are broken. As of Django-1.9, GIF-icons have been replaced by SVG-icons.

**Comment by FinalAngel** [comment]
@jrief we'd need to merge it then to 3.7

**Comment by jrief** [comment]
@FinalAngel Oh, no! It's really annoying that those icons in the admin are broken since Django-1.9.
This btw. is a bug-fix, not a feature, so should go into 3.5.4 or 3.6.1 respectively.

**Comment by czpython** [comment]
Yes, should land on 3.7 (develop), backport to 3.6.1 and then 3.5.4

**Comment by FinalAngel** [comment]
👍 @vThaian can you please plan this in?

**Comment by vThaian** [comment]
yes, sure. I created #6624 for this and then I will create backports for `3.6.X` and `3.5.X`

**Pull request merged**
