### PR TITLE
fixed toolbar placement when foundation is installed

### PR DESCRIPTION
**Pull request by genti94**
https://github.com/divio/django-cms/issues/5101

before
eff75c80-0aee-11e6-9302-b6540f326b75
after
f6a487e2-0aee-11e6-98dd-066cccf43108

### CODE REVIEW

**Comment by vxsx** [comment]
👍

**Comment by vxsx** [comment]
Can you make sure it's updated with latest `release/3.2.x` and add a note in the changelog please?

**Comment by vxsx** [comment]
ping

**Comment by genti94** [comment]
@vxsx checked with latest release/3.2.x updates and added to changelog

**Pull request merged**
