### PR TITLE
Fixed #5858 -- Double slashes in admin login url

### LINKED ISSUE #5858: Double slashes in admin login url
### Summary
After deploy blank project by instruction:
http://docs.django-cms.org/en/latest/how_to/install.html

When we run server and open project in browser:
http://localhost:8000/

Our redirect to:
http://localhost:8000/admin/login/?next=//?edit

And after we authorization (paste login, password and press Login) we don't see administration interface (hold on login form):
image

If we repeat press button Login we see this page (CSRF is outdated):
image

### Expected behaviour
When we don't authenticated and we open:
http://localhost:8000/

And our redirect to:
http://localhost:8000/admin/login/?next=/?edit

#### Actual behaviour
When we don't authenticated and we open:
http://localhost:8000/

And our redirect to:
http://localhost:8000/admin/login/?next=//?edit

#### Environment

* Python version: 3.5.2
* Django version: 1.10.5
* django CMS version: 3.4.2

### PR DESCRIPTION
**Pull request by itcrab**
### Summary

Fixes #5858

### Proposed changes in this pull request
In my case I have only one language in LANGUAGES list. In url it don't placed (main page is: http://localhost:8000/). But redirect to admin login we paste current LANGUAGE_CODE in login url and take: "//?" (if we have more languages it will be "/ru/?" or "/en/?" as example).

I add little check to have or not LANGUAGE_CODE in current page.

### CODE REVIEW

**Comment by itcrab** [comment]
In my project I don't usage `i18n_patterns` - all urls don't starts with `/LANGUAGE_CODE/` (in future I don't needed more than one language).

**Comment by czpython** [comment]
Hello @itcrab,
Thanks for this.
Please rebase your PR with latest release/3.4.x branch.

ie. `git rebase release/3.4.x`

**Comment by itcrab** [comment]
@czpython output:
```
$ git branch
* fix-cms-3.4.2-login
  release/3.4.x

$ git rebase release/3.4.x
Current branch fix-cms-3.4.2-login is up to date.
```

**Comment by itcrab** [comment]
@czpython I mistake, one second)

**Comment by itcrab** [comment]
@czpython output:
```
$ git rebase release/3.4.x
First, rewinding head to replay your work on top of it...
Applying: Fix double slashes in admin login url
```

**Comment by itcrab** [comment]
@czpython done

**Comment by czpython** [comment]
Hello @itcrab,
Did you pull in the latest changes from release/3.4.x branch and then rebase?
Somehow it still shows commits outside of this pr..

**Comment by itcrab** [comment]
@czpython yes
image
---
image

**Comment by itcrab** [comment]
@czpython I right?

**Comment by itcrab** [comment]
@czpython test is fixed:
- failes: https://travis-ci.org/divio/django-cms/builds/196307066
- fixes: https://travis-ci.org/divio/django-cms/builds/198096211

**Comment by czpython** [comment]
@itcrab did you do a `push --force` after the rebase?

**Comment by itcrab** [comment]
@czpython I pushed changes from PyCharm

Are you not see any commits?

**Comment by itcrab** [comment]
@czpython all tests is success (allowed failure is three fails)

**Comment by itcrab** [comment]
@czpython please waiting - I redo your needs

**Comment by itcrab** [comment]
@czpython finished rebase - waiting tests results

**Comment by itcrab** [comment]
@czpython all tests is finished:
- in first commit all tests is success
- in second commit one of tests is failed (CasperJS)

**Comment by itcrab** [comment]
@czpython ping

all tests is done success

**Comment by czpython** [comment]
Thank you very much @itcrab!

**Pull request merged**
