### PR TITLE
Issues/fix breadcrumbs

### LINKED ISSUE #4041: Breadcrumbs may disappear in one of published/draft mode

### PR DESCRIPTION
**Pull request by mkoistinen**
Fixes #4041

### CODE REVIEW

**Comment by mkoistinen** [comment]
@yakky please review, thanks.

**Comment by yakky** [comment]
LGTM, but I'd add a test for #4041

**Comment by yakky** [comment]
Tested in live cases and it's +1 for me, but we need a test for the case that's supposed to fix

**Comment by mkoistinen** [comment]
Test(s) coming...

**Comment by mkoistinen** [comment]
Rebased

**Comment by yakky** [comment]
@mkoistinen do you need help with tests? This is definitely and urgently needed in both 3.0 and 3.1

**Comment by mkoistinen** [comment]
@yakky, actually, ~~I think~~ I need help with the code itself. As of *now* (in this branch) here's what works:

1. CMSApp (normal) apps with menus declared within them work as expected;
1. CMSConfigApp apps with menus declared within them work as expected;
1. In these cases, the attach menu setting in the advanced setting correctly only shows a single item and the correct menu items are displayed in the corresponding menus.

Here's what doesn't:
When we do not declared the menus inside the CMSApp/CMSConfigApp class, but rather allow the user to independently assign the menu in the advanced settings. In this case, things get confused.

For example, if you have CMSConfigApp app with a CMSAttachMenu registered, then you hook this app to 2 or more pages and manually assign the CMSAttachMenu to them, it is not guaranteed that the correct instance of the CMSAttachMenu gets assigned to each page.

Is this even possible?

**Comment by yakky** [comment]
@mkoistinen I'll give it a run on my way to cardiff

**Comment by yakky** [comment]
@mkoistinen can't reproduce the described behavior with your test project. Assigign multi menu to multi-a and multi-b pages, publishing and reloading the project provides dropdown wih "menu-a" and "menu-b" items

**Comment by mkoistinen** [comment]
Merging this as a partial solution which is then augmented with #4159.

**Comment by mkoistinen** [comment]
Thanks, @yakky, this definitely helps with this issue. I think there are still some edge cases that need to be addressed, but I'll open new issues specifically for these.

**Pull request merged**
