### PR TITLE
Adds Django and Python versions to debug bar info tooltip

### PR DESCRIPTION
**Pull request by mkoistinen**

### CODE REVIEW

**Comment by yakky** [comment]
LGTM

**Comment by czpython** [comment]
Django has a get_version() utility but wasn't documented until very recently. :+1:

**Comment by yakky** [comment]
I retrack my LGTM: __version__ does not exist until 1.8
We have to use get_version()

**Comment by mkoistinen** [comment]
Thanks to both of you =)

**Pull request merged**
