### PR TITLE
#4423: added hook for using custom query sets for plugins

### PR DESCRIPTION
**Pull request by o-zander**
Improvement for #4423

### CODE REVIEW

**Comment by yakky** [comment]
@o-zander nice!
@mkoistinen are you with merging this for 3.2? 
@evildmp do we need any docs for this?

**Comment by mkoistinen** [comment]
This is nice. Would like to see this get into 3.2.

**Comment by mkoistinen** [comment]
@o-zander, Tests aren't passing. Some of this may be my fault (working on them now), but there are some tests failing because of this API change.

**Comment by mkoistinen** [comment]
Actually, I don't think this does require any docs changes... committing...

**Comment by mkoistinen** [comment]
@o-zander I've committed this in, but we still need to fix the tests.

**Comment by mkoistinen** [comment]
Actually, reverting until we have tests that pass.

**Comment by o-zander** [comment]
I nearly changed anything except a little wrapper func so I'm very suprised this breaks something. Maybe it helps to use objects instead of _default_manager. Then there isn't really a change at all. But I will have a look at it. Could be a little bit difficult for me to distinguish your test failures from the one caused by the api change ;)

**Comment by o-zander** [comment]
Opened a new merge request: #4556

**Pull request merged**
