### PR TITLE
Empty All in placeholder remove plugins from all the localized version of the page

### PR DESCRIPTION
**Pull request by pevar**
Solve Issue #3880

### CODE REVIEW

**Comment by yakky** [comment]
Nice, thanks!

**Comment by yakky** [comment]
How about writing a test for this?

**Comment by mkoistinen** [comment]
I'd like to get this into 3.0.11, which has a target "cutoff point" of 28-Feb.

**Comment by yakky** [comment]
@pevar do you need any help to write the tests to get this merged?

**Comment by pevar** [comment]
Yes please, first time for me.

**Comment by yakky** [comment]
@pevar steps are:

 * create a page
 * create a few plugins (see https://github.com/divio/django-cms/blob/support/3.0.x/cms/tests/plugins.py#L324-L336)
 * create a title (this means: translate the page at first step by using create_title) as in https://github.com/divio/django-cms/blob/support/3.0.x/cms/tests/multilingual.py#L182
 * add plugins to the title (as in step 2, but setting the language according to the title you just created)
 * use login_context to login as admin (https://github.com/divio/django-cms/blob/support/3.0.x/cms/tests/admin.py#L82)
 * run the clear_placeholder view (as in https://github.com/divio/django-cms/blob/support/3.0.x/cms/tests/admin.py#L1149-L1151) (by default it runs in english)
 * after the view has run check that the placeholder still contains plugin in the other language (something like `self.assertEqual(ph_en.get_plugins().count(), #)` would do, where "#" is the number of plugins you added in step 4

Join #django-cms IRC channel for further help

**Comment by pevar** [comment]
@yakky 
Thanks, which module in test folder I should put my code in?

**Comment by yakky** [comment]
I think ``cms.tests.admin`` is the best one

**Comment by yakky** [comment]
@pevar wow, really nice!
Te failing test it's just a pyflake check, you just need to adjust the test code style (please see the failure text on travis or run ``develop.py test cms.AboveStaticAnalysisCode`` on you local machine)

**Comment by pevar** [comment]
@yakky, it's not really clear to me what travis is saying. I've now removed some unused variables to get the style right.

**Comment by yakky** [comment]
@pevar exactly :)
We have this pyflake check in the testsuite that runs pyflake on the codebase and it fails if pyflake report some issues.
You can run this check locally with `develop.py test cms.AboveStaticAnalysisCode`

**Comment by yakky** [comment]
@mkoistinen LGTM

**Comment by yakky** [comment]
@mkoistinen this may be ported to support/3.0.x too, I think

**Comment by yakky** [comment]
@pevar congrats for your first contribution to django CMS, well done!

**Comment by pevar** [comment]
@yakky thanks for the help! I'm very happy to contribute.

**Pull request merged**
