### PR TITLE
Django 1.8 support

### LINKED ISSUE #3993: django 1.8
Is there an expected timeframe for support of Django 1.8?

### LINKED ISSUE #4023: Update language middleware for Django 1.8
The language middleware needs an update because the key `django_language` has been deprecated in Django 1.7. 

From the [docs](https://docs.djangoproject.com/en/1.7/releases/1.7/#internationalization):
> The LocaleMiddleware now stores the user’s selected language with the session key _language.  This should only be accessed using the LANGUAGE_SESSION_KEY constant. Previously it was stored with the key django_language and the LANGUAGE_SESSION_KEY constant did not exist, but keys reserved for Django should start with an underscore. For backwards compatibility django_language is still read from in 1.7. Sessions will be migrated to the new key as they are written.

Django 1.8 drops backwards compatibility.

### PR DESCRIPTION
**Pull request by yakky**
Fix #4023
Fix #3993
Fix #4025

### CODE REVIEW

**Comment by saeedsq** [comment]
Waiting for django-cms release supporting django 1.8

**Comment by blueyed** [comment]
@yakky 
Django 1.8 is not listed in the docs / requirements (https://django-cms.readthedocs.org/en/latest/how_to/install.html#requirements)

**Comment by sergei-maertens** [comment]
Is there an ETA on PyPI release?

**Comment by yakky** [comment]
3.1.1 with Django 1.8 support has been released a couple of weeks ago (3.1.2 it's the latest available as of now)

**Pull request merged**
