### PR TITLE
fix get User model in 0010 migration

### PR DESCRIPTION
**Pull request by igorkud90**

### CODE REVIEW

**Comment by yakky** [comment]
@igorkud90 Could you elaborate this?

**Comment by igorkud90** [comment]
@yakky I have a custom User model. When i apply migrations on empty database, i have a error: ProgrammingError: column User.same_field does not exist. This field added in my 0004 migration in my app, but django-cms migrations perfomed before this 0004 migration. We can't import the User model directly as it may be a newer version than this migration expects. We can use the historical version.

**Comment by yakky** [comment]
@igorkud90 I'll merge this into support branch with a further fix for south migration.
Thanks for spotting it

**Comment by yakky** [comment]
Linked PR merged

**Pull request closed without merging**
