### PR TITLE
Fixed #5502 -- AttributeError when using create_page in management command

### LINKED ISSUE #5502: del _thread_locals.user -> AttributeError: user
Get a strange error, while usage of **cms.api.create_page()** in a management command e.g.:
```
blog_page = create_page(
    title=_("blog"),
    template="foo/bar.html",
    language="en",
    apphook="BlogApp",
    apphook_namespace="djangocms_blog",
    in_navigation=True
)
...
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
...
  File "/home/jens/PyLucid_env/lib/python3.5/site-packages/cms/api.py", line 274, in create_page
    del _thread_locals.user
AttributeError: user
```

The Problem is:
```
...
  File "/home/jens/PyLucid_env/lib/python3.5/site-packages/cms/api.py", line 220, in create_page
    application_urls = _verify_apphook(apphook, apphook_namespace)
  File "/home/jens/PyLucid_env/lib/python3.5/site-packages/cms/api.py", line 83, in _verify_apphook
    apphook_pool.discover_apps()
  File "/home/jens/PyLucid_env/lib/python3.5/site-packages/cms/apphook_pool.py", line 68, in discover_apps
    load('cms_app')
  File "/home/jens/PyLucid_env/lib/python3.5/site-packages/cms/utils/django_load.py", line 65, in load
    get_module(app, modname, verbose, failfast)
  File "/home/jens/PyLucid_env/lib/python3.5/site-packages/cms/utils/django_load.py", line 49, in get_module
    module = import_module(module_name)
```
importlib.import_module() will be import **djangocms_blog** and this will remove  "user" from "_thread_locals".

### PR DESCRIPTION
**Pull request by jedie**
Fixed #5502

### CODE REVIEW

**Comment by jedie** [comment]
> I believe this (_thread_locals.user) is no longer necessary

Maybe, i don't know ;)

**Comment by czpython** [comment]
Ping @jedie :)

**Comment by jedie** [comment]
@czpython done. rebased to release/3.3.x

**Comment by czpython** [comment]
Thanks!

**Pull request merged**
