### PR TITLE
Fixed delete button

### PR DESCRIPTION
**Pull request by Croden**
Hardcoded "delete/" link leads to `404` - changed this to be same as "submit_line" from django itself.

### CODE REVIEW

**Comment by czpython** [comment]
Hello @Croden,
Thank you very much for this contribution.
I've been quite busy this week, but will definitely review your pr no later than the weekend.

**Comment by czpython** [comment]
Hello @Croden,
Which django version are you using?

**Comment by haricot** [comment]
It works with django 1.8 and django-cms 3.4 but not with django 1.9 and 1.10

**Comment by haricot** [comment]
Just an example to quickly show what happens on this issue when we try to delete an extension object:
 
> Page not found (404)
> Request Method: GET
> The current URL, /fr/admin/project/iconextension/15/change/delete/, didn't match any of these.

This URL should be :

/fr/admin/project/iconextension/iconextension/15/delete/

**Comment by czpython** [comment]
Thanks for the clarification @haricot.
And thanks to @Croden for the patch :)

**Comment by czpython** [comment]
Merged in d90102f61014e822fc863dbf0eb9e82bf6e02898

**Pull request closed without merging**
