### PR TITLE
add `?_popup=1` to add apphook url

### PR DESCRIPTION
**Pull request by vxsx**
to fix the popup not dismissing correctly in django 1.8

### CODE REVIEW

**Comment by mkoistinen** [comment]
LGTM =)

**Comment by FinalAngel** [comment]
Sweet :+1:

**Comment by mkoistinen** [comment]
@vxsx Shouldn't we have logic here to use '?' or '&' depending on the url itself?

**Comment by vxsx** [comment]
I don't think so, as it never has it in the apphook urls

**Comment by FinalAngel** [comment]
agreed, even if, normally you have the popup param first (or last) doing evaluation here is overkill

**Comment by mkoistinen** [comment]
Well, the url comes from a method which can be overridden by the developer in their own apphook. Someone may wish to include their own GET params at some point. At that point, this may break.

**Pull request merged**
