### PR TITLE
Fixes issue #4334

### LINKED ISSUE #4334: Getting a JS error when using custom change_form in plugins.
Getting ``Uncaught Error: Syntax error, unrecognized expression: #id_page_link_2 option[value=]`` on this [``$("#id_%(name)s_2 option[value=]")``](https://github.com/divio/django-cms/blob/59761231b7053ab1bbb9c6a3e860a39cd1f54621/cms/forms/widgets.py#L107) when using a custom change_form for a plugin. We have another select2 in there. 
Adding a ``try,catch`` around it worked for us - even omitting the ``else`` branch...  Will create a PR in case it's confirmed by others.

### PR DESCRIPTION
**Pull request by FinalAngel**
We also need to separate the JavaScript from the python code, this will be another PR though.

Fix #4334

### CODE REVIEW

**Comment by vxsx** [comment]
oh my
codewise LGTM

**Comment by yakky** [comment]
@FinalAngel @vxsx I'm going to port this fix in support, merging it there and forward porting all the way up

**Comment by FinalAngel** [comment]
@yakky awesome :)

**Comment by yakky** [comment]
Fixed in #4486

**Pull request closed without merging**
