### PR TITLE
Refs #4580 -- Drop support for Django 1.6, 1.7 and Python 2.6.

### LINKED ISSUE #4580: [META] Dropping 1.6 and code cleanup
Probably not fully pep8/isort compliant at first but let's tackle this

**Dropping django 1.6**:
- [x] #4581

**From #3802**:
- [x] `setup.py`: Python 2.6 classifier and minimum Django version (south also?)
- [x] `from __future__ import with_statement` (for Python 2.6)
- [x] Replace `SortedDict` with `collections.OrderedDict` (need Python 2.7 min.)
- [x] `cms.test_utils.compat` (skipIf unittest2 stuff) (need Python 2.7 min.)
- [x] Usage of `cms.utils.compat.DJANGO_1_6`
- [x] Replace from `django.utils.importlib` with `importlib` (need Python 2.7 min.)

**Other Issues**:
- [x] #3064

### PR DESCRIPTION
**Pull request by timgraham**

### CODE REVIEW

**Comment by timgraham** [comment]
@yakky this is ready for review.

**Comment by yakky** [comment]
@timgraham awesome, I really like the addition / deletion ratio :)
Just waiting for develop to be opened for 3.3 submission

**Comment by FinalAngel** [comment]
great work @timgraham I hope to get a decision today so we can move forward with develop being 3.3!

**Comment by yakky** [comment]
@timgraham thanks, this is great. Inaugurating the 3.3 development path with this PR!

**Pull request merged**
