### PR TITLE
Sane add plugin

### PR DESCRIPTION
**Pull request by ojii**
attempts to fix the testing issues in #3516

### CODE REVIEW

**Comment by ojii** [comment]
i'm done with this.

**Comment by yakky** [comment]
@ojii giving up? any way we can overcome this?

**Comment by ojii** [comment]
> @ojii giving up? any way we can overcome this?

yes I'm giving up. I'm just wasting time fighting travis and don't think that's a productive use of my time.

**Comment by yakky** [comment]
@ojii apart from travis problems, is the rest fine?

**Comment by ojii** [comment]
@yakky from what I can tell, yes. again I'm happy to address any issues that arise with my actual code. But I'm no loner happy to waste hours on travis.

**Comment by yakky** [comment]
@ojii I reopen this and I will find a way to get around running frontend tests problem.
I'll try other -more deterministic- environment to get this running

**Comment by yakky** [comment]
@ojii I have local failures for ``AddPluginTest``:
    ======================================================================
    ERROR: test_add_plugin_in_text_plugin (cms.tests.frontend.AddPluginTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/srv/repo/django-cms-3.0/cms/tests/frontend.py", line 612, in test_add_plugin_in_text_plugin
        self.wait_page_loaded()
    File "/srv/repo/django-cms-3.0/cms/tests/frontend.py", line 140, in wait_page_loaded
        self.wait_loaded_tag('body')
    File "/srv/repo/django-cms-3.0/cms/tests/frontend.py", line 131, in wait_loaded_tag
        timeout
    File "/srv/repo/django-cms-3.0/cms/tests/frontend.py", line 122, in wait_until
        WebDriverWait(self.driver, timeout).until(callback)
    File "/var/local/venvs/cms-3.1/local/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 63, in until
        value = method(self._driver)
    File "/srv/repo/django-cms-3.0/cms/tests/frontend.py", line 130, in <lambda>
        lambda driver: driver.find_element_by_tag_name(tag_name),
    File "/var/local/venvs/cms-3.1/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 326, in find_element_by_tag_name
        return self.find_element(by=By.TAG_NAME, value=name)
    File "/var/local/venvs/cms-3.1/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 662, in find_element
        {'using': by, 'value': value})['value']
    File "/var/local/venvs/cms-3.1/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 173, in execute
        self.error_handler.check_response(response)
    File "/var/local/venvs/cms-3.1/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
        raise exception_class(message, screen, stacktrace)
    WebDriverException: Message: [JavaScript Error: "a.document.getElementsByTagName(...)[0] is undefined" {file: "file:///tmp/tmp51yNP4/extensions/fxdriver@googlecode.com/components/command-processor.js" line: 8900}]'[JavaScript Error: "a.document.getElementsByTagName(...)[0] is undefined" {file: "file:///tmp/tmp51yNP4/extensions/fxdriver@googlecode.com/components/command-processor.js" line: 8900}]' when calling method: [nsICommandProcessor::execute]


    ======================================================================
    ERROR: test_add_style_plugin (cms.tests.frontend.AddPluginTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/srv/repo/django-cms-3.0/cms/tests/frontend.py", line 524, in test_add_style_plugin
        self._login()
    File "/srv/repo/django-cms-3.0/cms/tests/frontend.py", line 101, in _login
        self.driver.get(url)
    File "/var/local/venvs/cms-3.1/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 185, in get
        self.execute(Command.GET, {'url': url})
    File "/var/local/venvs/cms-3.1/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 173, in execute
        self.error_handler.check_response(response)
    File "/var/local/venvs/cms-3.1/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
        raise exception_class(message, screen, stacktrace)
    WebDriverException: Message: [JavaScript Error: "e is null" {file: "file:///tmp/tmp51yNP4/extensions/fxdriver@googlecode.com/components/command-processor.js" line: 7854}]'[JavaScript Error: "e is null" {file: "file:///tmp/tmp51yNP4/extensions/fxdriver@googlecode.com/components/command-processor.js" line: 7854}]' when calling method: [nsICommandProcessor::execute]

On Circle CI situation looks better (I get the same failures as above), but I still get timeout errors for the entire testsuite :/

**Comment by yakky** [comment]
By using --xvfb the tests run fine on Circle CI, except for the two failures above
What selenium driver are you using locally, standard firefox one?

**Comment by yakky** [comment]
At least the second issue is related to an alert popping up "There was an error creating the plugin." during the tests.

**Comment by ojii** [comment]
have this working again locally, but requires #3706 merged as I based my work off that

**Comment by ojii** [comment]
anybody know why there's two travis runs for this, maybe @yakky?

**Comment by yakky** [comment]
@ojii consistently failing (even after multiple restart)
I'll try to reproduce it locally

**Comment by ojii** [comment]
the one failing is testing a weird commit though. from what I can see the one passing is testing the right one.

**Comment by ojii** [comment]
Moved to #4369

**Pull request closed without merging**
