### PR TITLE
Fixes #5828 - Create page wizard on new site works inconsistently

### LINKED ISSUE #5828: Create page wizard on new site works inconsistently
When launching a new django CMS project, the content creation wizard **under some circumstances:**

* **does not** work when invoked from the *Add the first page* link on the splash screen
* **does not** work if it opens automatically
* **does** work if you use the **Create** button in the toolbar.

When it fails, it says: "Please choose an option from below to proceed to the next step.".

screenshot 2016-12-27 16 45 49.

I can replicate this on a manually set up project running Django 1.9.12 and django CMS 3.4.1, but not on a project set up using the django CMS installer.

### PR DESCRIPTION
**Pull request by SteinRobert**
- uses `get_language_from_request()` for `wizard_language` context
   variable now

### Summary

This PR contains the requested changes from @czpython in #5981.

Fixes #5828
Resolves #5981 

### Links to related discussion
#5981 

### Proposed changes in this pull request
Get language from request instead from form/context processor. The wizard basically relied on the CMS using the i18n context processor.

I'm afraid to say I did not come up with a good idea for a test though. It seems like doing a `POST` to the wizard endpoint is not working since there are no entries to select. Any ideas on how to get the `choice_wrapper` div filled for a test case, so that there is actually a choice to submit? I'm glad to add a test if someone has a suggestion how it could look like.

### CODE REVIEW

**Comment by czpython** [comment]
Hello @SteinRobert,
Thanks for your contribution.
Can you rebase the pr with latest release/3.4.x branch?

**Comment by SteinRobert** [comment]
Rebased.

**Comment by czpython** [comment]
Thanks @SteinRobert.
Looks like there's an unrelated change in the decorators.py

**Comment by SteinRobert** [comment]
Oh well, sorry. Seems like another PR interfered with this one. Removed it.

**Comment by czpython** [comment]
Thanks!

**Pull request merged**
