### PR TITLE
Proposal: sharper icon font using fixed 16px font-size

### PR DESCRIPTION
**Pull request by SachaMPS**
Hi guys,
this is the same pull request for my proposal but as requested in the develop branch.

@vxsx Checked the scissor icon. It only appears to be cut off because it exceeds the artboard. This is for purpose and icon rendering is not affected. In the screenshot below you can see how it looks on my screen.
image

I also changed the resize icon a bit. to be more crisp.. Please compare it to the old one...
image

Saludos,
Sacha

### CODE REVIEW

**Comment by vxsx** [comment]
not sure if we should keep old variables and default them to generic `$icon-size` for end-user flexibility or not

LGTM, @FinalAngel can you take a look?

**Comment by mkoistinen** [comment]
LGTM

**Comment by FinalAngel** [comment]
good for me @yakky :1 for merge

**Comment by yakky** [comment]
@SachaMPS thanks for this contribution!

**Pull request merged**
