### PR TITLE
Fix page move

### LINKED ISSUE #3820: Exception when adding sibling page
In a clean project if I create a Home page, then two child pages (Child 1, Child 3), then attempt to add a sibling in between (Child 2) I get the following traceback:

    Environment:

    Request Method: POST
    Request URL: http://localhost:9000/en-us/admin/cms/page/add/?language=en-us&target=3&position=right

    Django Version: 1.7.4
    Python Version: 3.4.2
    Installed Applications:
    ('djangocms_admin_style',
     'djangocms_text_ckeditor',
     'django.contrib.auth',
     'django.contrib.contenttypes',
     'django.contrib.sessions',
     'django.contrib.admin',
     'django.contrib.sites',
     'django.contrib.sitemaps',
     'django.contrib.staticfiles',
     'django.contrib.messages',
     'cms',
     'treebeard',
     'menus',
     'sekizai',
     'djangocms_link',
     'reversion',
     'my_demo')
    Installed Middleware:
    ('django.contrib.sessions.middleware.SessionMiddleware',
     'django.middleware.csrf.CsrfViewMiddleware',
     'django.contrib.auth.middleware.AuthenticationMiddleware',
     'django.contrib.messages.middleware.MessageMiddleware',
     'django.middleware.locale.LocaleMiddleware',
     'django.middleware.doc.XViewMiddleware',
     'django.middleware.common.CommonMiddleware',
     'django.middleware.clickjacking.XFrameOptionsMiddleware',
     'cms.middleware.user.CurrentUserMiddleware',
     'cms.middleware.page.CurrentPageMiddleware',
     'cms.middleware.toolbar.ToolbarMiddleware',
     'cms.middleware.language.LanguageCookieMiddleware')

    Traceback:
    File "../lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
      111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
    File "../lib/python3.4/site-packages/django/contrib/admin/options.py" in wrapper
      583.                 return self.admin_site.admin_view(view)(*args, **kwargs)
    File "../lib/python3.4/site-packages/django/utils/decorators.py" in _wrapped_view
      105.                     response = view_func(request, *args, **kwargs)
    File "../lib/python3.4/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
      52.         response = view_func(request, *args, **kwargs)
    File "../lib/python3.4/site-packages/django/contrib/admin/sites.py" in inner
      206.             return view(request, *args, **kwargs)
    File "../src/django-reversion/src/reversion/revisions.py" in do_revision_context
      296.                 return func(*args, **kwargs)
    File "../src/django-cms/cms/admin/pageadmin.py" in add_view
      410.         return super(PageAdmin, self).add_view(request, form_url, extra_context=extra_context)
    File "../lib/python3.4/site-packages/django/contrib/admin/options.py" in add_view
      1453.         return self.changeform_view(request, None, form_url, extra_context)
    File "../lib/python3.4/site-packages/django/utils/decorators.py" in _wrapper
      29.             return bound_func(*args, **kwargs)
    File "../lib/python3.4/site-packages/django/utils/decorators.py" in _wrapped_view
      105.                     response = view_func(request, *args, **kwargs)
    File "../lib/python3.4/site-packages/django/utils/decorators.py" in bound_func
      25.                 return func.__get__(self, type(self))(*args2, **kwargs2)
    File "../lib/python3.4/site-packages/django/db/transaction.py" in inner
      394.                 return func(*args, **kwargs)
    File "../lib/python3.4/site-packages/django/contrib/admin/options.py" in changeform_view
      1404.                 self.save_model(request, new_object, form, not add)
    File "../src/django-cms/cms/admin/pageadmin.py" in save_model
      246.                 language,
    File "../src/django-cms/cms/models/managers.py" in set_or_create
      151.             return self.create(**data)
    File "../lib/python3.4/site-packages/django/db/models/manager.py" in manager_method
      92.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
    File "../lib/python3.4/site-packages/django/db/models/query.py" in create
      372.         obj.save(force_insert=True, using=self.db)
    File "../lib/python3.4/site-packages/django/db/models/base.py" in save
      589.                        force_update=force_update, update_fields=update_fields)
    File "../src/django-cms/cms/models/titlemodels.py" in save_base
      89.         ret = super(Title, self).save_base(*args, **kwargs)
    File "../lib/python3.4/site-packages/django/db/models/base.py" in save_base
      613.                                   update_fields=update_fields)
    File "../lib/python3.4/site-packages/django/dispatch/dispatcher.py" in send
      198.             response = receiver(signal=self, sender=sender, **named)
    File "../src/django-cms/cms/signals/title.py" in pre_save_title
      40.         instance.page.save(no_signals=True)
    File "../src/django-cms/cms/models/pagemodel.py" in save
      444.                 self.save_base(**kwargs)
    File "../src/django-cms/cms/models/pagemodel.py" in save_base
      467.         return super(Page, self).save_base(*args, **kwargs)
    File "../lib/python3.4/site-packages/django/db/models/base.py" in save_base
      617.             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
    File "../lib/python3.4/site-packages/django/db/models/base.py" in _save_table
      679.                                       forced_update)
    File "../lib/python3.4/site-packages/django/db/models/base.py" in _do_update
      723.         return filtered._update(values) > 0
    File "../lib/python3.4/site-packages/django/db/models/query.py" in _update
      600.         return query.get_compiler(self.db).execute_sql(CURSOR)
    File "../lib/python3.4/site-packages/django/db/models/sql/compiler.py" in execute_sql
      1004.         cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
    File "../lib/python3.4/site-packages/django/db/models/sql/compiler.py" in execute_sql
      786.             cursor.execute(sql, params)
    File "../lib/python3.4/site-packages/django/db/backends/utils.py" in execute
      81.             return super(CursorDebugWrapper, self).execute(sql, params)
    File "../lib/python3.4/site-packages/django/db/backends/utils.py" in execute
      65.                 return self.cursor.execute(sql, params)
    File "../lib/python3.4/site-packages/django/db/utils.py" in __exit__
      94.                 six.reraise(dj_exc_type, dj_exc_value, traceback)
    File "../lib/python3.4/site-packages/django/utils/six.py" in reraise
      658.             raise value.with_traceback(tb)
    File "../lib/python3.4/site-packages/django/db/backends/utils.py" in execute
      65.                 return self.cursor.execute(sql, params)
    File "../lib/python3.4/site-packages/django/db/backends/sqlite3/base.py" in execute
      485.         return Database.Cursor.execute(self, query, params)

    Exception Type: IntegrityError at /en-us/admin/cms/page/add/
    Exception Value: UNIQUE constraint failed: cms_page.path

### PR DESCRIPTION
**Pull request by yakky**
Fix #3820

### CODE REVIEW

**Comment by yakky** [comment]
@jsma would please test this?

**Comment by jsma** [comment]
Grabbing lunch but will test as soon as I get back, thanks!

**Comment by jsma** [comment]
LGTM! I missed the fact that django-cms wraps the `MP_Tree.move()` calls to return a reloaded object. That gives us a consistent way of handling this then and alleviates some of my general concerns. Did you already review all types of tree modification calls or did you primarily focus on `move()` calls for now? I haven't fully thought it through but do you foresee any similar issues with `add_root()`,  `add_child()` or `add_sibling()`?

**Comment by jsma** [comment]
I realize now that *you* wrapped the `move()` call in this very PR. I confused myself bouncing between branches earlier and thought this must have already been in develop, guess I didn't overlook it after all. Good call on adding it in!

**Comment by yakky** [comment]
@jsma nope, it's been added in this PR.
This makes Page / CMSPlugin not consistent with treebeard API, but it's a small price for a much more robust implementation on our side

**Pull request merged**
