### PR TITLE
Cleaned up some compatibility shims for old Django versions.

### PR DESCRIPTION
**Pull request by timgraham**

### CODE REVIEW

**Comment by yakky** [comment]
Great job!
I'm setting this on hold to allow @ojii 's patch in first to avoid merge conflicts

**Comment by timgraham** [comment]
Rebased and fixed test failure on develop.

**Comment by yakky** [comment]
Awesome, thanks!

**Comment by yakky** [comment]
The sane-add-plugin patch will require some time before merging, resuming merging

**Pull request merged**
