### PR TITLE
added screenshots to site-wide content tutorial

### PR DESCRIPTION
**Pull request by darioalbanesi**
screenshots for side wide content

full_screen

### CODE REVIEW

**Comment by mkoistinen** [comment]
Nice additions, can you fix this:

    sphinx.errors.SphinxWarning: /home/travis/build/divio/django-cms/docs/user/tutorial/30-structure-\
    content-modes.rst:47: WARNING: image file not readable: user/tutorial/images/structure-button.png

**Comment by evildmp** [comment]
@mkoistinen don't worry I will catch all errors before merging into develop.

**Comment by evildmp** [comment]
@darioalbanesi thanks, looks like *just* what we need.

One question: how easy is it to add a nice big title text to the header, that is superimposed on the image? It could be added in the next section (advanced styling).

**Comment by evildmp** [comment]
Will merge this in the meantime.

**Comment by darioalbanesi** [comment]
@evildmp something like this?
title_header

**Comment by evildmp** [comment]
@darioalbanesi yes, but is that text in the image - or superimposed via the CMS (the latter is what I suggest)

**Comment by darioalbanesi** [comment]
@evildmp cms of course ;) I added a style-plugin for the feature-visual and used an extra class to align the text to the center. Used H1 and a custom text-color (which is the brand-primary color)

**Pull request merged**
