### PR TITLE
Sync develop with support/3.0.x

### PR DESCRIPTION
**Pull request by yakky**
Last merge from support/3.0.x to develop.

### CODE REVIEW

**Comment by yakky** [comment]
@ojii @mkoistinen @evildmp are you ok to merge this?

**Comment by mkoistinen** [comment]
Wow, great job on getting all this to merge. I'm sure it was a pain. +1 from me!

**Comment by digi604** [comment]
nice

**Comment by yakky** [comment]
Way less painful than anticipated

**Comment by ojii** [comment]
gonna be honest, this is too big to properly review for me but I want this merged! we still have some time to fix develop should this break stuff.

**Comment by yakky** [comment]
@ojii more a request for an ack on the *way* to merge this, not a code review which is kind of impossible :D

**Pull request merged**
