### PR TITLE
Add documentation for plugins datamigration

### LINKED ISSUE #4357: Unknown column 'cms_cmsplugin.level when running plugin migrations
For example, migrating Aldryn Events:

```
./manage.py migrate aldryn_events 
/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/parler/forms.py:198: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form EventAdminForm needs updating 
return super(TranslatableModelFormMetaclass, mcs).__new__(mcs, name, bases, attrs)

Operations to perform: 
Apply all migrations: aldryn_events 
Running migrations: 
Applying aldryn_events.0007_set_default_namespaces...Traceback (most recent call last): 
File "./manage.py", line 10, in <module> 
execute_from_command_line(sys.argv) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line 
utility.execute() 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute 
self.fetch_command(subcommand).run_from_argv(self.argv) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv 
self.execute(*args, **options.__dict__) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute 
output = self.handle(*args, **options) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle 
executor.migrate(targets, plan, fake=options.get("fake", False)) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate 
self.apply_migration(migration, fake=fake) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration 
migration.apply(project_state, schema_editor) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 105, in apply 
operation.database_forwards(self.app_label, schema_editor, project_state, new_state) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 117, in database_forwards 
self.code(from_state.render(), schema_editor) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/aldryn_events/migrations/0007_set_default_namespaces.py", line 32, in create_default_namespaces 
app_config__isnull=True)) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 141, in __iter__ 
self._fetch_all() 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all 
self._result_cache = list(self.iterator()) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator 
for row in compiler.results_iter(): 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 701, in results_iter 
for rows in self.execute_sql(MULTI): 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql 
cursor.execute(sql, params) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute 
return super(CursorDebugWrapper, self).execute(sql, params) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute 
return self.cursor.execute(sql, params) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__ 
six.reraise(dj_exc_type, dj_exc_value, traceback) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute 
return self.cursor.execute(sql, params) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute 
return self.cursor.execute(query, args) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute 
self.errorhandler(self, exc, value) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler 
raise errorclass, errorvalue 
django.db.utils.OperationalError: (1054, "Unknown column 'cms_cmsplugin.level' in 'field list'")
```

The migration is trying to use the old (Django MPTT) ``level`` attribute, which no longer exists.

### PR DESCRIPTION
**Pull request by yakky**
Fix #4357

### CODE REVIEW

**Comment by czpython** [comment]
@yakky suggestion looks good to me. thanks.

**Comment by czpython** [comment]
@yakky just saw that the attribute on django native migrations is called ```run_before```, so maybe we also add this as well?

**Comment by yakky** [comment]
@paulo isn't it already mentioned in the PR?

**Comment by czpython** [comment]
@yakky ah haha yes, I will now focus on only one thing at a time :)

**Pull request merged**
