### PR TITLE
Fixed #6572 -- Added missing clear cache for menu when page moved

### LINKED ISSUE #6572: Menu link is broken when page moved
### Summary

Moving page and try access with menu link, but link is broken.

This affect also breadcrumb.

I think the cause is Page.move_page execute clear_cache without clearing menu cache.

### Expected behaviour

Update menu cache when page moved.

### Actual behaviour

Menu link is broken when page moved.

### Environment

* Python version: 3.6.5
* Django version: 1.11.17
* django CMS version: 3.5.3

### PR DESCRIPTION
**Pull request by air-hand**
### Summary

Fixes #6572 

### Proposed changes in this pull request

Clear menu cache with other caches when page moved.

### Documentation checklist

* [x] I have updated CHANGELOG.txt if appropriate
* [ ] I have updated the release notes document if appropriate, with:
    * [ ] general notes
    * [ ] bug-fixes
    * [ ] improvements/new features
    * [ ] backwards-incompatible changes
    * [ ] required upgrade steps
    * [ ] names of contributors
* [ ] I have updated other documentation
* [ ] I have added my name to the AUTHORS file
* [ ] This PR's documentation has been approved by Daniele Procida

### CODE REVIEW

**Comment by air-hand** [comment]
I faced #6572 on v3.5.3 but created this PR based on 3.6.x, because v3.5.3 is planned as last version of 3.5.x.

If I need PR to 3.5.x branch, please tell me.

**Comment by vThaian** [comment]
great, it works 👍

**Comment by vThaian** [comment]
@air-hand I created PR with a test for your change

**Comment by air-hand** [comment]
Thanks! @vThaian 
This commits already merged by #6590, so I close

**Pull request closed without merging**
