### PR TITLE
 Override urlconf_module so that Django system checks don't crash.

### LINKED ISSUE #6717: Upgrading to Django 2.2.x gives No module named 'app_resolver'
### Summary

After upgrading from Django 2.1.11 to 2.2.4, any django management command fails to run when there are cms apphooks in the app. This behavior can reproduced with the versions 3.6.x and 3.7.0rc1.

#### Traceback

```python
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/urls/resolvers.py", line 409, in _check_custom_error_handlers
    handler, param_dict = self.resolve_error_handler(status_code)
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/urls/resolvers.py", line 592, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/urls/resolvers.py", line 572, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/sounak/.pyenv/versions/3.6.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app_resolver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sounak/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/sounak/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/urls/resolvers.py", line 399, in check
    messages.extend(check_resolver(pattern))
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/urls/resolvers.py", line 399, in check
    messages.extend(check_resolver(pattern))
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/urls/resolvers.py", line 399, in check
    messages.extend(check_resolver(pattern))
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/urls/resolvers.py", line 400, in check
    messages.extend(self._check_custom_error_handlers())
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/urls/resolvers.py", line 411, in _check_custom_error_handlers
    path = getattr(self.urlconf_module, 'handler%s' % status_code)
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/sounak/.pyenv/versions/python-test/lib/python3.6/site-packages/django/urls/resolvers.py", line 572, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/sounak/.pyenv/versions/3.6.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app_resolver'
```

### Environment

* Python version: 3.6.5
* Django version: 2.1.11
* django CMS version: 3.6.x, 3.7.0rc1

### PR DESCRIPTION
**Pull request by lddubeau**
### Summary

Fixes #6717 

### General checklist

* [x] I have updated the CHANGELOG.txt

(I don't think this is necessary as this falls under the "Introduced Django 2.2 support." rubric.)

* [x] I have created backports if necessary

(Not necessary.)

* [x] I have updated the documentation and/or amended the upgrade section
      if necessary

(Not necessary.)

### CODE REVIEW

**Comment by FinalAngel** [comment]
@yakky @czpython could you have a look at this, would be awesome to release it in an RC2 :)

**Comment by lddubeau** [comment]
I've force-pushed a simplification just now. The original `FakeModule` rigmarole is unnecessary: `urlconf_module` can evaluate to a list of patterns instead of an object with a `urlpatterns` attribute.

**Comment by yakky** [comment]
@FinalAngel @lddubeau LGTM at first sight, I'm checking a bit more in depth later today
Anyway this should target release/3.7.x branch, right?

**Comment by FinalAngel** [comment]
@yakky it's good to target develop, I'll backport then to 3.7.x :)

**Comment by yakky** [comment]
@lddubeau @FinalAngel LGTM, I also tested in a project with fairly complex apphooks, and everything looks ok

**Comment by lddubeau** [comment]
@yakky I also ran the proposed changed with a complex Django project of mine that uses Django CMS. Some of the Django tests don't test apphooks specifically but they do depend on them working properly. The Selenium-based tests access the site as a regular user would, so they also depends on apphooks working fine. All tests passed without problem.

**Comment by FinalAngel** [comment]
awesome, I'll be merging this PR tomorrow and prepare an RC2 release with it. @yakky anything else from your end that should also be included in the RC2?

**Comment by yakky** [comment]
@FinalAngel I haven't spotted anything relevant for RC2

**Pull request merged**
