### PR TITLE
Faster login in frontend tests

### PR DESCRIPTION
**Pull request by ojii**
Drastically speeds up frontend tests (some basic timing I made locally showed that tests that use ``_fastlogin`` instead of ``_login`` are about 2x as fast (``PlaceholderBasicTests`` ran in ~9s instead of ~20s).

The way this works is by using the Django login (``django.contrib.auth.authenticate``/``django.contrib.auth.login``) and setting the session cookie in selenium.

### CODE REVIEW

**Comment by ojii** [comment]
@yakky (or anyone else) review?

**Comment by yakky** [comment]
@ojii LGTM, ready for merge?

**Comment by ojii** [comment]
@yakky ready from my side

**Comment by mkoistinen** [comment]
:+1:

**Comment by yakky** [comment]
@ojii more goodies in!

**Comment by mkoistinen** [comment]
I vote we revert this. It causes tests to fail, for example in cms.tests.test_frontend.PlaceholderBasicTests on Mac OS.

**Pull request merged**
