### PR TITLE
replaced various images

### PR DESCRIPTION
**Pull request by genti94**
Can't add placeholders on add-text-plugin.png

all images under http://docs.django-cms.org/en/latest/user/index.html replaced

### CODE REVIEW

**Comment by vxsx** [comment]
check https://github.com/vxsx/django-cms/pull/1#issuecomment-146078451

**Comment by evildmp** [comment]
I'll work on the text for this.

**Comment by mkoistinen** [comment]
:+1:

**Comment by FinalAngel** [comment]
:+1:

**Comment by vxsx** [comment]
docs/images/page-basic-settings.png and save-and-continue have wrong settings button sizes

**Comment by vxsx** [comment]
and button colors for that matter

**Comment by mkoistinen** [comment]
Gentian, can you rebase this with latest develop so tests will pass?

**Pull request merged**
