### PR TITLE
Use CMS_CACHE_DURATIONS, when configured

### PR DESCRIPTION
**Pull request by mkoistinen**
Should address #4931.

### CODE REVIEW

**Comment by mkoistinen** [comment]
Deeper changes need to be made. I've rebased this for release/3.2.x.

**Comment by mkoistinen** [comment]
These tests are failing:
cms.tests.test_cache.CacheTestCase.test_cache_page
cms.tests.test_cache.CacheTestCase.test_cache_placeholder
cms.tests.test_cache.CacheTestCase.test_invalidate_restart
cms.tests.test_cache.CacheTestCase.test_no_cache_plugin
cms.tests.test_menu.SoftrootTests.test_basic_home
cms.tests.test_permissions.PermissionCacheTests.test_basic_permissions
cms.tests.test_permissions.PermissionCacheTests.test_permission_manager
cms.tests.test_rendering.RenderingTestCase.test_render_placeholder_tag_use_cache
cms.tests.test_templatetags.NoFixtureDatabaseTemplateTagTests.test_show_placeholder_for_page_marks_output_safe
cms.tests.test_views.ContextTests.test_context_current_page

Will have to dig deeper later.

**Comment by yakky** [comment]
@mkoistinen @czpython see #4986 (which is against 3.0: I think this is a serious issue and even if no more 3.0 is planned, I think it's worth to have it in)

**Comment by yakky** [comment]
Fixed in #4986

**Pull request closed without merging**
