### PR TITLE
Fixed an issue when link plugin couldn't be edited

### PR DESCRIPTION
**Pull request by vxsx**
Since #5429 the plugin markup has `cms-plugin` class, which means
that link plugins markup would look like `<a class="cms-plugin" ...>`
which wasn't handled by that doubleclick handler that previously
allowed editing of plugins that contain links.

does not require backporting

### CODE REVIEW

**Comment by FinalAngel** [comment]
LGTM

**Comment by czpython** [comment]
@vxsx Is there a test for this?

**Comment by vxsx** [comment]
@czpython nope

**Comment by vxsx** [comment]
@czpython now there is :)

**Comment by vxsx** [comment]
screen shot 2016-07-05 at 09 23 58

**Pull request merged**
