### PR TITLE
Merge 3.1 into 3.2

### PR DESCRIPTION
**Pull request by yakky**

### CODE REVIEW

**Comment by mkoistinen** [comment]
OK to merge

**Comment by czpython** [comment]
Ok to merge

**Comment by yakky** [comment]
@mkoistinen @czpython @vxsx merging!

**Comment by vxsx** [comment]
it's missing compiled bundles (`gulp bundle`) 
as long as we don't forget to do that before release 👍

**Comment by yakky** [comment]
@vxsx bundle added, merging this

**Pull request merged**
