### PR TITLE
re-added support for custom AUTH_USER_MODEL

### PR DESCRIPTION
**Pull request by ojii**
Alternative implementation for #4365

### CODE REVIEW

**Comment by yakky** [comment]
@ojii I like this :100:

**Comment by ojii** [comment]
Guess I can go fight some more 2.6! Fun times!

Btw if you like this PR you'll love this: http://django-app-manage.readthedocs.org/en/latest/ (it's a start)

**Comment by ojii** [comment]
@yakky tests flipped to green

**Comment by yakky** [comment]
awesome!

**Pull request merged**
