### PR TITLE
Fix redirection

### LINKED ISSUE #3654: Delete page shouldn't result in 404
Currently when you delete a page, the user is redirected to the url of the page that was just deleted. It should instead redirect to the parent page, if one exists or to the home page rather than giving the user an error page.

### LINKED ISSUE #3655: Save after updating slug should redirect to new slug
Currently if you change the slug for a page and save, you are redirected back to the page at the old slug, which gives a 404 error. The user should instead be redirected to the page's new slug.

### LINKED ISSUE #3766: 404 when logging out after creating a new page without publishing
I get a 404 with the following steps:
- Login to cms
- create a new page
- leave it unpublished
- logout via toolbar menu sitename > logout username

Might be related to #2770

### LINKED ISSUE #3895: Document redirection behavior
A proper documentation for redirection when in frontend mode must be written.

Currently the behavior is the following:
- after creating or editing a new page or a model with toolbar which implements ``Toolbar.watch_models`` (see #3889) the frontend is redirected to the instance absolute URL
- after deleting the object, frontend is redirected to the home page (a better behavior would be to redirect the user to the parent page)
- after logout, user is redirected to the home page (ditto)

### PR DESCRIPTION
**Pull request by yakky**
Fix #3766 by redirecting anonymous users to the home page
Fix #3654 by not reloading the page after setting the new URL
Fix #3655 by not reloading the page after setting the new URL
Fix #3895 by documenting redirection behavior

This depends on #3892 

Linked to #3889 to document the attribute needed to handle redirection with normal Django models

### CODE REVIEW

**Comment by yakky** [comment]
@mkoistinen this must be thoroughtfully checked.

**Comment by yakky** [comment]
refactoring of redirection logic to take unpublished pages into account

**Comment by mkoistinen** [comment]
Pushed to 3.0.12 to get more time for testing this rather sizeable PR.

**Comment by evildmp** [comment]
Looking at docs now

**Comment by mkoistinen** [comment]
This really needs to have supporting tests, IMHO.

**Comment by yakky** [comment]
@mkoistinen tests are already included in this PR

**Comment by mkoistinen** [comment]
My bad, sorry. Assigning myself for testing.

**Pull request merged**
