### PR TITLE
Open and close collapsible trees using alt key

### PR DESCRIPTION
**Pull request by astagi**
Implements #3747

### CODE REVIEW

**Comment by yakky** [comment]
Ping @mkoistinen @FinalAngel for review

**Comment by FinalAngel** [comment]
codewise all good, question is, if we want the "alt" key to trigger this

**Comment by yakky** [comment]
Alt is not the best option in my opinion as it triggers window moving on Linux

**Comment by astagi** [comment]
What about "shift"?

**Comment by FinalAngel** [comment]
I'd rather use a combo of Shift + E (for expand) or something similar

**Comment by astagi** [comment]
@FinalAngel do you mean Shift + E + click on the placeholder? In that case it won't behave as a toggle (close all if open, open all otherwise on key+click).

**Comment by mkoistinen** [comment]
It is unnatural already to use SHIFT for the advanced page settings shortcut. I think its time we used ALT for Macs, and SHIFT for linux for both this and for the advanced page setting shortcut.

**Comment by yakky** [comment]
@mkoistinen AFAIK in the page tree the Shift is used on any operating system (https://github.com/divio/django-cms/blob/develop/cms/static/cms/js/modules/cms.changelist.js#L564)

**Comment by astagi** [comment]
any update here?

**Comment by FinalAngel** [comment]
alright +1 for shift key

**Comment by astagi** [comment]
Thank you @FinalAngel I'll update this PR later :)

**Comment by FinalAngel** [comment]
awesome @astagi

**Comment by astagi** [comment]
Updated! :tada:

**Comment by mkoistinen** [comment]
+1

**Comment by FinalAngel** [comment]
:+1:

**Comment by yakky** [comment]
Awesome @astagi

**Pull request merged**
