### PR TITLE
Issue #6342: Extended the docs of `text_enabled` param for plugins

### PR DESCRIPTION
**Pull request by jeroenpeters1986**
### Summary
Added a little bit more information on `text_enabled` to help developers discover this powerful feature

### Links to related discussion
I reported this in issue #6342, which has been moved to https://github.com/divio/djangocms-text-ckeditor/issues/478

### Proposed changes in this pull request
Just some additions to the docs of djangocms-text-ckeditor

### Documentation checklist

* [x] I have updated CHANGELOG.txt if appropriate
* [x] I have updated the release notes document if appropriate, with:
    * [x] general notes
    * [x] bug-fixes
    * [x] improvements/new features
    * [x] backwards-incompatible changes
    * [x] required upgrade steps
    * [x] names of contributors
* [x] **I have updated other documentation**
* [x] **I have added my name to the AUTHORS file**
* [ ] This PR's documentation has been approved by Daniele Procida

### CODE REVIEW

**Comment by czpython** [comment]
Hello @jeroenpeters1986,
Thanks for your contribution.

As mentioned in https://github.com/divio/django-cms/issues/6342,
the `text_enabled` attribute is a feature from the djangocms-text-ckeditor application which is separate from the django CMS core.

We will be removing that section entirely from the core documentation on 3.6.x as it is just left over from previous releases of the cms that bundled the text plugin.

I'm open to landing this on the documentation for versions <= 3.5.x.
@evildmp thoughts?

**Comment by jeroenpeters1986** [comment]
Hi @czpython, will there be place for the docs in the new repo? I could not find that yet

**Comment by jeroenpeters1986** [comment]
:-( Build failed, but I find it hard to believe the docs did that..

**Comment by czpython** [comment]
@jeroenpeters1986 
Because we're removing this section from the docs on 3.6.x, please create a new pull request, targeting the release/3.5.x branch. I'll back port it to 3.4.x.

On cms >= 3.6.x, information about the `text_enabled` will live on the README of djangocms-text-ckeditor.

**Comment by jeroenpeters1986** [comment]
I will, thank you :-) I will also chekout the README of djangocms-text-ckeditor

**Pull request closed without merging**
