### PR TITLE
Fixed #6035 -- Editing advanced settings raises AttributeError

### LINKED ISSUE #6035: Editing advanced settings through change view raises AttributeError
### Summary

Editing advanced settings for a page through the change view of page admin raises an error if djangocms_blog is an installed app.

AttributeError: This QueryDict instance is immutable error is raised

### Expected behaviour

Advanced settings for a page should be successfully modified through page admin change view.

#### Actual behaviour

AttributeError: This QueryDict instance is immutable is raised at cms/admin/forms.py at line 305:

  del self.data['application_configs']

self is django.http.request.QueryDict({'application_namespace': '', 'reverse_id': '', 'xframe_options': '0', 'site': '1', 'application_urls': '', 'template': 'base.html', 'csrfmiddlewaretoken': 'foo', 'redirect': '', 'language': 'en', 'overwrite_url': '', 'navigation_extenders': '', '_save': 'Save'  })

app is a djangocms_blog.cms_apps.BlogApp

app_configs is like {'BlogApp': <djangocms_blog.cms_apps.BlogApp object at foo>}

app_namespaces is {'BlogApp': 'djangocms_blog'}

#### Environment

* Python version: 3.5
* Django version: 1.11.4 (But this error is non-specific to latest Django)
* django CMS version: 3.4.3

### PR DESCRIPTION
**Pull request by olibook**
### Summary

Fixes #6035

### Proposed changes in this pull request

copy the QueryDict before mutation.

### CODE REVIEW

**Comment by olibook** [comment]
please let me know your feedback

**Comment by thagat** [comment]
Is someone checking these pull requests? I'm having problems with this bug and this pull request solves it.

**Comment by czpython** [comment]
Thanks for the pr @olibook.
I'll have a look on the first week of January.

**Comment by jedie** [comment]
Any news? Happens here too, with django-cms==3.4.5 and Django==1.11.9

**Comment by SteinRobert** [comment]
Same here. This makes it impossible to add applications to a page.

**Comment by czpython** [comment]
@olibook 
Thanks for the initial patch.
I pushed a different fix in https://github.com/divio/django-cms/pull/6250

**Pull request closed without merging**
