### PR TITLE
translate string 'Language independent options'

### PR DESCRIPTION
**Pull request by treavis**

### CODE REVIEW

**Comment by yakky** [comment]
@mkoistinen I guess we can merge this by cherry picking the commit to support and forward port with later merge back

**Comment by mkoistinen** [comment]
OK. @yakky, please leave this open for now, I'll remove the 3.0.13 tag once I've cherry picked it, and relabel for 3.x.

**Comment by yakky** [comment]
@mkoistinen :+1:

**Comment by mkoistinen** [comment]
OK, this was cherry-picked into support/3.0.x: d3dfda74

**Comment by yakky** [comment]
Closed by #4034

**Pull request closed without merging**
