### PR TITLE
Fixed #5564 -- Removed html5lib from setup.py

### LINKED ISSUE #5564: Drop html5lib as a dependency
The new release of html5lib has caused several issues for new installations, given that we don't use this library directly (it's used by djangocms-text-ckeditor), I suggest we drop it.

/cc @divio/django-cms-core

### PR DESCRIPTION
**Pull request by czpython**
Fixed #5564

@divio/django-cms-core  Please review.

### CODE REVIEW

**Comment by evildmp** [comment]
Don't forget to mention "Removed html5lib from setup.py" in the CHANGELOG.

**Comment by evildmp** [comment]
Looks good to go @czpython!

**Comment by yakky** [comment]
LGTM

**Comment by czpython** [comment]
@yakky 
I think we'll have to rebase with 3.1.x and 3.2.x, then forward port to 3.3.x and develop.
Thoughts?

**Comment by czpython** [comment]
Closed in favor of https://github.com/divio/django-cms/pull/5584

**Pull request closed without merging**
