### PR TITLE
FE Integration and unit tests

### PR DESCRIPTION
**Pull request by vxsx**
This pull request adds frontend unit tests written in Jasmine and frontend integration tests written in casperjs

Also features some modifications to frontend files, with little change to functionality (regarding cms-toolbar-expanded class)

also updates node_packages

### CODE REVIEW

**Comment by yakky** [comment]
Is this for 3.3 or 3.4?

**Comment by vxsx** [comment]
this was supposed to be for 3.4, but there is no reason not to have tests earlier @yakky

**Comment by yakky** [comment]
@vxsx I am not at all against merging this in 3.3! :) I was just confused because included docs states this for 3.4

**Comment by vxsx** [comment]
ouch, the coverage :D

**Comment by FinalAngel** [comment]
- Need to adapt changelog
- Missing documentation on the integration tests
- We eventually also need to mention what "skip istanbul" means

**Comment by FinalAngel** [comment]
nice LGTM ready to merge

**Comment by yakky** [comment]
@FinalAngel @vxsx 
I'm surprised how this enormous amount of tests actually **lowers** the coverage. Does the new coverage includes all the frontend code? Just curious, LGTM too

**Comment by vxsx** [comment]
@yakky that's exactly the case, it includes the js files, and they are not covered fully
here's a screenshot of coverage from my local machine (i'm have some wip tests)

screen shot 2016-03-24 at 14 16 25

but currently it's lower on what's pushed (e.g. navigation is 22% vs 100%)

**Comment by yakky** [comment]
@vxsx it's awesome!! :smile:  Is this ready for merge?

**Comment by vxsx** [comment]
this one is, yes :) more will follow

**Comment by yakky** [comment]
@vxsx good, merging, then

**Pull request merged**
