### PR TITLE
Raise 404 instead of returing it

### LINKED ISSUE #4451: AttributeError: 'Http404' object has no attribute 'has_header' when publish page
This is caused by returning `Http404` instead of raising it.
https://github.com/divio/django-cms/blob/3.1.3/cms/admin/pageadmin.py#L972

This is a regression in 3.0.x caused by this commit https://github.com/divio/django-cms/commit/b37b73aa75047bdc12c4d346853cce2e443cad80

I will provide I pull request after several minutes

### PR DESCRIPTION
**Pull request by vstoykov**
Fixes #4451

### CODE REVIEW

**Comment by yakky** [comment]
probably worth merging in support branches too

**Comment by evildmp** [comment]
@vstoykov This should be covered by a test already (not sure where it would be exactly), but if there isn't one, we need one.

**Comment by vstoykov** [comment]
I will try to find a proper place to put the test and will update my pull request

**Comment by mkoistinen** [comment]
@vstoykov is this still on your radar?

**Comment by vstoykov** [comment]
Hi guys sorry for the delay. I was busy these days.

I also had some problems with running tests on my machine. I'm not sure if it is related with newer version of Firefox or something else but at the end I just ran the tests related to publishing process `test_publisher` (where I put my test).

I rebased my PR to current `develop`. I see that you put milestone `3.0.16` and this means that someone of you @yakky @mkoistinen will backport it right?

**Comment by yakky** [comment]
@vstoykov yes. Will do. Thanks for taking your time ti complete this pr

**Comment by vstoykov** [comment]
There are some problems with the tests with which I'm not familiar. Can you guys check the output of the travis?

**Comment by vxsx** [comment]
@vstoykov it seems some of the jobs were cancelled, I restarted them

**Comment by yakky** [comment]
@vstoykov all good now. @vxsx I'll merge first into support branch. I 'll take care of this

**Comment by yakky** [comment]
Fixed in support. Will forward port
Thanks @vstoykov for reporting this!

**Pull request closed without merging**
