### PR TITLE
Fixes Issue #3782

### PR DESCRIPTION
**Pull request by peterfarrell**
The circular import issue with this leaves something to be desired....

### CODE REVIEW

**Comment by peterfarrell** [comment]
Let me know how you want the pretty up the circular import issue that was discussed with @yakky on IRC.  That is why the build is failing...

**Comment by yakky** [comment]
@peterfarrell thanks for this.
I'm trying a more radical approach to remove the circular import thing. I'll be back to this shortly

**Comment by yakky** [comment]
Fix #3782

**Comment by yakky** [comment]
Circular import should be solved by #3828

**Comment by yakky** [comment]
Plase rebase on current develop. Circular imports should be solved

**Comment by yakky** [comment]
@peterfarrell could your rebase / recheck this on current develop? Circular imports should be solved

**Comment by peterfarrell** [comment]
@yakky  - looks like the circular import fix works.

**Comment by yakky** [comment]
Great. This PR was about the unique, index, right?

**Comment by peterfarrell** [comment]
Yes, it had to do with the unique index and the circular imports.

**Comment by yakky** [comment]
Ok, will you reopen this rebased on devleop?

**Comment by peterfarrell** [comment]
I did rebase on develop. I merged divio develop into my develop and then rebased my branch.

**Comment by yakky** [comment]
Changes in the model is missing here, apparently

**Comment by peterfarrell** [comment]
Looks the rebase overwrote that. I just added that.

**Comment by yakky** [comment]
Thanks @peterfarrell !

**Pull request merged**
