### PR TITLE
Fixed #6340 -- Reorder models to support dumpdata

### LINKED ISSUE #6340: dumpdata/loaddata cycle not working anymore
### Summary

dumping database (esp. PageModels) using dumpdata and reinstalling them using loaddata leads to:

Exeption: TreeNode matching query does not exist.

### Expected behaviour

should work.

### Actual behaviour

Exception.

### Environment

* Python version: 2.7
* Django version: 1.11
* django CMS version: 3.5.0 and up

### PR DESCRIPTION
**Pull request by heppstux**
Fixes #6340

### CODE REVIEW

**Comment by czpython** [comment]
@heppstux can you add a changelog entry, you'd have to add first add 3.5.3 (unreleased) and then put it under that.

**Comment by heppstux** [comment]
@czpython, changelog is updated.

**Comment by czpython** [comment]
Thanks!

**Comment by jrief** [comment]
I just retested this patch, loading a fixture generated using
```
./manage.py dumpdata --natural-foreign cms > fixture.json
./manage.py loaddata fixture.json
```

However, it still doesn't work. Reason is, that `cms.signals.page.pre_save_page()` is invoked for each `cms.Page` instance while loading the fixture. At that time, the table for `cms.TreeNode` is not filled yet, hence accessing `page_instance.node` raises a `ObjectDoesNotExist` exception.

**Pull request merged**
