### PR TITLE
[WIP] menu_tags context's stack bug

### PR DESCRIPTION
**Pull request by DylannCordel**
Because context.update add a new level in the Context's stack and because there is never a context.pop called in menu_tags, the context AFTER a menu_tags call is not the same than BEFORE the call and some funny things happen.

## How to reproduce

onecolum.html :

```
<h1>Dolly vs Magic Pony Fight</h1>
{% block main %}
<div id="maincolumn">some content</div>
{% endblock %}
```

twocolumns.html :

```
{% extends "one_olumn.html" %}
{% load menu_tags %}
{% block main %}
    {% with template='Magic Pony is the best !' %}
        <h2>{{ template }}</h2>
        {% block sidebar %}
            <aside>
                But Dolly could be a problem !
                {% show_sub_menu 1 %}
                <h2>{{ template }}</h2>
            </aside>
        {% endblock %}
        {{ block.super }}
    {% endwith %}
{% endblock %}
```

### Expected Result

When twocolumns.html is rendered, we should have :

```
<h1>Dolly vs Magic Pony Fight</h1>
<h2>Magic Pony is the best !</h2>
<aside>
    But Dolly could be a problem !
    <h2>Magic Pony is the best !</h2>
</aside>
<div id="maincolumn">some content</div>
```

### Current Result

But when twocolumns.html is rendered, we currently have :

```
<h1>Dolly vs Magic Pony Fight</h1>
<h2>Magic Pony is the best !</h2>
<aside>
    But Dolly could be a problem !
    <h2>menu/sub_menu.html</h2>
</aside>
<aside>
    But Dolly could be a problem !
    <h2>menu/sub_menu.html</h2>
</aside>
```

### CODE REVIEW

**Comment by yakky** [comment]
@ojii @DylannCordel sorry, I got a bit lost here. After the change in classy-tags, what's the recommended and proper fix (apart from the failures in the testsuite)

**Comment by DylannCordel** [comment]
Hi @yakky 
IMHO, we should modify the menu_tag to use `InclusionTag.push_context` and rewrite test without any assertion than we have menu_tag context content in the "main" context after its execution.

Are you okay with this ?

**Comment by yakky** [comment]
A lot of work / cleanup has been done in #4085 in this respect. I have not targeted this specific issue, though
It may worth  another run by using that branch

**Comment by yakky** [comment]
@DylannCordel could you recheck the latest develop and latest classy-tags?
it should behave in a saner way

**Comment by DylannCordel** [comment]
@yakky : I just tested with the master branch of classy-tags and develop for cms : probem is different but still here. I (force) push my branch to just add a test for this.
I tried to correct this, but when I try to use your new `push_context` for `ShowSubMenu`, I get this error :

```
  File "/home/cordeld/workspace/opensource/django-cms/test-django-cms/src/django-classy-tags/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/cordeld/workspace/opensource/django-cms/test-django-cms/src/django-classy-tags/classytags/helpers.py", line 81, in render_tag
    safe_context = flatten_context(context)
  File "/home/cordeld/workspace/opensource/django-cms/test-django-cms/src/django-classy-tags/classytags/utils.py", line 85, in flatten_context
    return context.flatten()
  File "/home/cordeld/workspace/opensource/django-cms/test-django-cms/local/lib/python2.7/site-packages/django/template/context.py", line 106, in flatten
    flat.update(d)

ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

Currently, `show_menu` and `show_sub_menu` tags overrides the context with their own values for those keys :

* children
* template
* from_level
* to_level
* extra_inactive
* extra_active

If the correction to bring is difficult, I think this could be acceptable to just have a warning inside the doc to avoid the problem. If a user must "protect" its context from the above keys replacement, he just has to call show_submenu inside a dedicated block. e.g:

instead of the bugged one:
```
{% with template='Magic Pony' %}
{% show_sub_menu 1 %}
<h3>{{ template }}</h3><!-- Wrong : template = 'menu/sub_menu.html'-->
{% endwith %}
```

use:
```
{% with template='Magic Pony' %}
{% block enclosure %}{% show_sub_menu 1 %}{% endblock %}
<h3>{{ template }}</h3><!-- Correct : template = 'Magic Pony'-->
{% endwith %}
```

**Comment by FinalAngel** [comment]
@DylannCordel can you re-base this PR?

**Comment by FinalAngel** [comment]
please rebase and reopen <3

**Comment by DylannCordel** [comment]
@FinalAngel : in my todolist for this week

**Comment by FinalAngel** [comment]
@DylannCordel 👍  thanks for your patience!

**Pull request closed without merging**
