### PR TITLE
Fixes #4005

### LINKED ISSUE #4005: Circular dependency problem, if auth.User has been substituted
This is the problem:

``PageUser`` normally is derived from ``auth.User``, but if a customized User model is used, it inherits from that class.

This customized User class is loaded with other models, some of which may import models from the CMS, for instance ``PlaceholderField``. The latter imports ``PageUser`` which causes a circular dependency.

By separating the classes and moving some import statements into the calling functions, this problem can be fixed.

I will fix this.

### PR DESCRIPTION
**Pull request by jrief**
Fixes #4005 by moving potential circular dependencies into the calling functions.

This PR adds less magicness to ``permissionmodels.py``.

Renamed ``force_unicode`` -> ``force_text``, since thats the correct name.

Obsoletes PR #3975.

### CODE REVIEW

**Comment by mkoistinen** [comment]
Hi Jacob, what's the status on this one?

**Comment by jrief** [comment]
This patch fixes the problem, but for some combinations of Django and Python the unit tests fail. Grrr.

If 3.1 is ready, I will retry since then support, for Django-1.4 and 1.5 will be dropped.

**Comment by yakky** [comment]
@jrief 3.1 is due to release any day now

**Comment by mkoistinen** [comment]
What is the status of this PR?

**Comment by jrief** [comment]
closes via #4005

**Pull request closed without merging**
