### PR TITLE
Fix handling of --migrate option

### PR DESCRIPTION
**Pull request by yakky**

### CODE REVIEW

**Comment by yakky** [comment]
@mkoistinen @FinalAngel plz review (it's not elegant, and probably we should work a bit more on app-manage integration, but we can postpone that)

**Comment by FinalAngel** [comment]
@yakky just that I understand it correctly, if you would do:

``python manage.py --migrate --no-migrations`` which results in ````python manage.py --no-migrations``?

If this is correct, could we also display a warning, saying "You cannot provide --migrate when using --no-migrations"?

**Comment by yakky** [comment]
Yes ``--no-migrations`` "wins". How about something like **Both --migrate and --no-migrations have been provided. --no-migrations is in effect.**

**Comment by FinalAngel** [comment]
:+1: @yakky

**Pull request merged**
