### PR TITLE
Fix typo in travis

### PR DESCRIPTION
**Pull request by yakky**
This will force the use of latest pip, required for django 1.10 in python 2

### CODE REVIEW

**Comment by czpython** [comment]
LGTM

**Comment by yakky** [comment]
@czpython apparently I'm not authorized to merge this

**Comment by czpython** [comment]
@yakky Try once more? I think is because develop is protected branch. I've configured to allow core devs to push to it. Should work now.

**Comment by yakky** [comment]
Success!

**Pull request merged**
