### PR TITLE
Added missing word.

### PR DESCRIPTION
**Pull request by Eraldo**
`requires a server restart so should` => `requires a server restart so it should`

### CODE REVIEW

**Comment by FinalAngel** [comment]
thank you again @Eraldo also 👍 from my side @evildmp ?

**Comment by FinalAngel** [comment]
@Eraldo just one thing, can you open this PR to "develop"?

**Comment by Eraldo** [comment]
@FinalAngel Do you mean merging the patch to the forked develop branch?
(Just making sure I understand you correctly)

**Comment by FinalAngel** [comment]
@Eraldo no problem, you need to merge it against https://github.com/divio/django-cms/tree/develop we use develop for the next upcoming release.

**Comment by Eraldo** [comment]
Like that?:
https://github.com/divio/django-cms/pull/5216

**Pull request closed without merging**
