### PR TITLE
Fix order of which application urls are injected into urlpatterns

### PR DESCRIPTION
**Pull request by vstoykov**
This will fix problem when there are nested apphooks and urls of top level apphook are more greedy.

This fix is for Django CMS 3.0.x. I know that 3.1 but fix for it will be little different because of django-treebeard and we are not currently upgraded to 3.1.

I'm planning to add tests for that but first I need your opinion about the solutions of the problem.

### CODE REVIEW

**Comment by yakky** [comment]
Nice one!
Tests definitely needed, but a big fat +1 on  my side

**Comment by yakky** [comment]
BTW would you add a TODO comment to remember to port this to 3.1 when forward porting from 3.0.x branch?

**Comment by vstoykov** [comment]
I updated my pull request with tests.

**Comment by yakky** [comment]
Thanks @vstoykov !

**Comment by yakky** [comment]
:+1:

**Comment by yakky** [comment]
@mkoistinen is this something for 3.0? It's actualy a bugfix, but with potential backward incompatibilities (albeit incompatibilities based on a flawed implementation)

**Comment by yakky** [comment]
Fix by #4169

**Comment by mkoistinen** [comment]
LGTM, merging.

**Pull request closed without merging**
