### PR TITLE
Squash integration

### PR DESCRIPTION
**Pull request by emiquelito**
### Summary

I'd like to propose this patch to use [Squash.io](https://www.squash.io/) on this repository. I believe this will help developers and maintainers to quickly validate each PR on its own fully functional staging environment, and running on an isolated VM.

Please let me know what you think and if you have any questions, thanks.

### Links to related discussion

N/A

### Proposed changes in this pull request

Example of Django-CMS working with Squash:

https://squash-tmp1-nejdm.squash.io/
Login as admin/admin

It takes just a few minutes to load, and the environment will stay active for 3 hours in a row, you can restart as many times as needed, [more info here](https://www.squash.io/docs/how-it-works-quick-intro/).

Squash is free for Open Source, maintainers just need to [signup here](https://www.squash.io/sign-up/) and reach out to the [support](https://www.squash.io/support/) through the chat window and we will enable a **forever free** Open Source account **with higher limits than our regular free account**.  Once this is done, Squash will post a comment on each Pull Request [like this ](https://github.com/emiquelito/django-cms-2.0/pull/1)- see screenshot:

Screen Shot 2019-11-07 at 7 46 12 PM

Please note that in this PR we are also enabling the [Automated Checks feature](https://www.squash.io/docs/automated-checks/), see the last line in the YAML file. This will make Squash trigger a separate VM for each commit and give a pass or fail based on a success response. You can also extend this to run Selenium/Cypress and other tests on top of that Squash deployment.

See:

squash io integration by emiquelito · Pull Request  1 · emiquelito django-cms-2 0

### General checklist

I've not updated the CHANGELOG.txt yet, wanted to validate this with the team first.

* [ ] I have updated the CHANGELOG.txt
* [ ] I have created backports if necessary
* [ ] I have updated the documentation and/or amended the upgrade section
      if necessary

### CODE REVIEW

**Comment by FinalAngel** [comment]
@emiquelito thank you for your contribution. I'll have a look to see if it's a viable option. Though as we're an open source project we'd need to get an account from your support team :)

**Comment by emiquelito** [comment]
@FinalAngel thanks for your comment and let me know if you have any questions, we would love to help Django-CMS and bring value to the community.

> @emiquelito thank you for your contribution. I'll have a look to see if it's a viable option. Though as we're an open source project we'd need to get an account from your support team :)

Absolutely, and Squash is 100% free for Open Source, all you need is to signup and let us know and we will increase your account limits forever free.

**Comment by emiquelito** [comment]
Hey @FinalAngel just checking to see if you have any questions or feedback on this PR. Thanks

**Comment by FinalAngel** [comment]
@emiquelito not so far, currently preparing the 3.7.1 release and will get back to squash.io afterwards :)

**Comment by emiquelito** [comment]
Hey @FinalAngel hope all is well.

I noticed this PR was closed without a merge, do you mind giving me some thoughts on this? anything I can do to improve this PR or any requirements that we might need to support?

We would love to offer a free account to help Django-CMS, I love your project and I have worked with it for many years.

Thanks
Evandro

**Comment by FinalAngel** [comment]
@emiquelito we have had some structural changes leading to the formation of the django CMS Association now Governing django CMS. It has its own technical board that handles these cases. You can reach out directly via info@django-cms.org :)

**Pull request closed without merging**
