### PR TITLE
Fresh install django-cms with CMS_RAW_ID_USERS set to True throws exception

### PR DESCRIPTION
**Pull request by cstrap**
Environment:
* Django 1.7+
* django-cms 3.x+

How to reproduce the issue:
* install django-cms via django CMS installer and choosing
  * django and django-cms version according to environment above
  * keep the default values and the installer does all "boring things"
* Update `settings.py` with `CMS_PERMISSION = CMS_RAW_ID_USERS = True`
* delete `project.db`
* re-run `./manage.py migrate`

The result should be:
```
...
django.db.utils.OperationalError: no such table: auth_user
```

So, I provide a solution on this PR.

Maybe I'm wrong, but I didn't found other ways in order to have a fresh install that starts with `CMS_PERMISSION` and `CMS_RAW_ID_USERS` set to `True`, except to comment out the `CMS_RAW_ID_USERS = True` and uncomment the row after migrations.

Any suggestions are appreciated.
Thanks!

### CODE REVIEW

**Comment by mkoistinen** [comment]
LGTM

**Comment by yakky** [comment]
@cstrap looks good. I wonder why that function is triggered during a simple migration, though.
I'd apply this  to 3.1 and forwardport to develop/3.2

**Comment by yakky** [comment]
Fixed in #4723

**Comment by cstrap** [comment]
You're welcome! Thanks for merging!

Btw, I spent some time in debugging and I found that the function is triggered by the checks provided by admin apps on the inlines models.
In fact, if I run `./manage.py check` the resulting exception is the same.

**Pull request closed without merging**
