### PR TITLE
Fixes test for both old and new versions of cmsplugin-file

### PR DESCRIPTION
**Pull request by mkoistinen**

### CODE REVIEW

**Comment by yakky** [comment]
@mkoistinen it's already fixed in #4926

**Comment by mkoistinen** [comment]
Oh. Can we merge it then, because its preventing us from getting clean tests.

**Comment by yakky** [comment]
@mkoistinen merged

**Comment by yakky** [comment]
@mkoistinen sorry, I merged before your edit.
It's huge only because it contains updated translations

**Comment by yakky** [comment]
@mkoistinen feel free to revert.
IMO It's better to avoid merging different commit to fix the same things, though

**Comment by mkoistinen** [comment]
This needs to be merged

**Pull request merged**
