### PR TITLE
add placeholders_list to request.toolbar

### PR DESCRIPTION
**Pull request by vxsx**
to have correct order of placeholders in the template

/cc @mkoistinen

### CODE REVIEW

**Comment by yakky** [comment]
Wondering if instead we should add a DeprecationWarning and wait for 1 more release before removing toolbar.placeholders

**Comment by vxsx** [comment]
+1 for DeprecationWarning, but i'm not really sure how to do it correctly :)

**Comment by mkoistinen** [comment]
@yakky since this is an internal structure, I don't think we require a warning, but we'll definitely have a note in the release notes. As you can see, in this PR, we plan to remove the old in 3.3.0.

**Comment by FinalAngel** [comment]
@mkoistinen I'd suggest creating a ticket for 3.3 then to remove that line, otherwise comments get lost. I'm also not for a deprecation warning.

**Comment by yakky** [comment]
:+1: for comment in release notes and a ticket to track the removal
Ok to not have a warning

**Pull request merged**
