### PR TITLE
Add aldryn demo button

### PR DESCRIPTION
**Pull request by FinalAngel**
Make it easier for users who visit the GitHub repo to directly get a demo.

### CODE REVIEW

**Comment by vxsx** [comment]
:+1:

**Comment by yakky** [comment]
@FinalAngel why on master? The default branch is develop
Other than that LGTM

**Comment by FinalAngel** [comment]
@yakky so it's directly visible. Merging to develop would mean its available after 3.2 or am I misunderstanding something?

**Comment by yakky** [comment]
Nope, develop's README is the default one visible on github and RTFD

**Comment by FinalAngel** [comment]
Alright @yakky give me a second

**Pull request closed without merging**
