### PR TITLE
disable caching for alias plugins

### PR DESCRIPTION
**Pull request by sunfirester**
#5403

### CODE REVIEW

**Comment by yakky** [comment]
As a stop gap looks good

**Comment by sunfirester** [comment]
would something like cache = cmsplugin_ptr.cache work?

**Comment by yakky** [comment]
@sunfirester the cache setting is anyway on the plugin class, not the plugin model. 
Probably defininig ``get_cache_expiration`` (see https://github.com/divio/django-cms/blob/53fd43ec4b383d11e7fa258b130efb33263d6c73/cms/plugin_base.py#L194) in the alias plugin class (https://github.com/divio/django-cms/blob/develop/cms/cms_plugins.py#L30) will do.

Something like this should work::

    def get_cache_expiration(self, request, instance, placeholder):
        if instance.plugin.get_plugin_class().cache:
            return 0
        return None

**Comment by mkoistinen** [comment]
Both the `cache` attribute and the `get_cache_expiration` value should be inherited from the primary plugin. I think if we just set these to False/zero, we'll be trading one issue for another.

**Comment by sunfirester** [comment]
Thank you for your replies guys, I didn't even know about get_cache_expiration.
I agree about inheriting these values from the primary plugin. I will adjust my PR accordingly later today for you to review, and use yakky's suggestion in my project in the meanwhile.

**Comment by sunfirester** [comment]
I changed my PR to try to inherit caching. I see now why my PR was incorrect. If you guys have time, please let me know if you think this makes any sense. Thanks again for your help :)

**Comment by sunfirester** [comment]
My second attempt was wrong as well... I'm not sure how I could grab the cache attribute of the CMSPlugin inside of AliasPlugin.

**Comment by czpython** [comment]
Closing as inactive.
Feel free to open a new pull request based off the latest develop branch.

**Pull request closed without merging**
