### PR TITLE
backport fix #3881 from 3.1 branch : Empty All in placeholder remove plu...

### PR DESCRIPTION
**Pull request by olarcheveque**
(It's my first pull request. Please be explicit.)

I am not sure if I have to update the CHANGELOG since the release_info mention to reference all PR merged.

### CODE REVIEW

**Comment by yakky** [comment]
@olarcheveque could you merge back the updatd support/3.0.x branch?
An item in th 3.0.14 changelog would be awesome

**Comment by olarcheveque** [comment]
@yakky : is it ok?

**Comment by yakky** [comment]
@olarcheveque LGTM

**Comment by mkoistinen** [comment]
Looks great, thanks, @olarcheveque!

**Pull request merged**
