### PR TITLE
Add render_model_add_block tag

### PR DESCRIPTION
**Pull request by mkoistinen**
OK, this works nicely to satisfy #3873, but would be even better if ClassyTags would let me declare the nodelist block "argument" as, optional. Anyone know if this is possible?

### CODE REVIEW

**Comment by mkoistinen** [comment]
@ojii, is it possible to have a single, but optional block/nodelist defined?

**Comment by mkoistinen** [comment]
Thats odd. The GitHub integration with Travis says this build failed, but if you click through, it shows all passing tests...

**Comment by yakky** [comment]
Travis, go home, you're drunk! :)

**Comment by yakky** [comment]
@mkoistinen can you revert the doc change regarding ``render_model_add``? I have a fix for that
Or just leave it and I'll rebase my PR on top of this after the merge

**Comment by ojii** [comment]
> @ojii, is it possible to have a single, but optional block/nodelist defined in an InclusionTag?

No, not without a heavy dose of dark magic. "endblock detection" happens at parse time, not at render time. Argument processing (including the one that would signal if it should scan for an endblock or not) happens at render time.

**Comment by mkoistinen** [comment]
@yakky - done
@ojii, ok, thanks, this implementation will stand then.

**Pull request merged**
