### PR TITLE
Fixed bugs affecting multiple render_model_blocks on the same page

### PR DESCRIPTION
**Pull request by vxsx**
1. Ref: https://github.com/divio/django-cms/issues/5677
2. If multiple render_model_blocks were rendered on the same page (e.g.
  menu on top of the page and in the footer) only
  the first one would get event handlers.

### CODE REVIEW

**Comment by vxsx** [comment]
This also fixes https://github.com/divio/django-cms/issues/6012

**Comment by FinalAngel** [comment]
@vxsx could you rebase this to master and fix the conflicts? That be awesome.

**Comment by vxsx** [comment]
@FinalAngel this also requires some backend work, which is why it's been on hold for a while now

**Comment by FinalAngel** [comment]
I'm closing it then for now...

**Pull request closed without merging**
