### PR TITLE
Add is_page=True to cms menu nodes attributes

### LINKED ISSUE #4626: Detecting if menu item is associated with a page
So after fixing #4276 attrs['page'] is no longer available in menu nodes. My question is whether there is a way for a menu modifier (or any other code dealing with menus for that matter) to tell if a particular node points to a page.

To put this into a context, I have a use-case where I need to display images (provided by djangocms-page-meta) along with menu items. The best way to do this for me would be subclassing ShowSubMenu template tag and adding image url to node attrs. However if code hits apphook menu items and node.id still matches an existing page id I cannot get a page object reliably.

### PR DESCRIPTION
**Pull request by skirsdeda**
Fixes #4626. Discussion in the bug report.

### CODE REVIEW

**Comment by skirsdeda** [comment]
I think it would make sense to backport this to 3.0/3.1/3.2 since #4276 was fixed back in 3.0.

**Comment by yakky** [comment]
3.0 and 3.1 are in pure support mode and, albeit small, this is a new feature.
I think it can qualify for 3.2.1, though.
@FinalAngel @mkoistinen ?

**Comment by FinalAngel** [comment]
would be fine for me in 3.2.x, @skirsdeda would you mind adding an entry to the changelog?

**Comment by yakky** [comment]
@skirsdeda still interested in getting this in?

**Comment by skirsdeda** [comment]
@yakky sorry for the lag. I'll finish this up tomorrow.

**Comment by skirsdeda** [comment]
@yakky Added a changelog entry and updated docs a bit. That should be it.

**Comment by yakky** [comment]
@skirsdeda awesome, thanks!

**Comment by yakky** [comment]
@skirsdeda merged in 3.2. Thanks!

**Pull request closed without merging**
