### PR TITLE
Small documentation fixes

### PR DESCRIPTION
**Pull request by mcavigelli**
Some fixes I have found while reading the docs.
Unfortunately I was not able to run the *make spelling*.

Make with virtualenv caused some access denied errors.

Matthias

### CODE REVIEW

**Comment by mcavigelli** [comment]
It says the changes lead to a failing check: what can I do to resolve that?
Or is it just a test artifact? It seems, that some builds before or after had problems with the same testcase.
Thanks for your advice, Matthias

**Comment by yakky** [comment]
@mcavigelli issue is already solved in 3.2 branch. We need to forwardport the changes to develop, after which you can simply merge develop on your branch (or rebase your branch on top of new develop).
It may take some days, though, as we're about to ship 3.2.1 and we will sync develop after this.
But that's not an issue when reviewing your PR

**Comment by yakky** [comment]
LGTM, summoning @evildmp for the final ok

**Comment by evildmp** [comment]
All looks good to me. Just restarting tests, not sure why they should fail.

**Comment by evildmp** [comment]
Merged in #5077, thanks @mcavigelli

**Pull request closed without merging**
