### PR TITLE
CMS Toolbar unit tests

### PR DESCRIPTION
**Pull request by vxsx**
49.82% → 92.28%

also some fixes to the toolbar itself

### CODE REVIEW

**Comment by FinalAngel** [comment]
LGTM though its pretty long

**Comment by vxsx** [comment]
test failures are related to https://github.com/divio/django-cms/pull/5113

**Comment by czpython** [comment]
:+1: I guess tests fail for another reason now?

**Comment by vxsx** [comment]
@czpython presumably because of https://github.com/divio/django-cms/pull/5113

**Comment by czpython** [comment]
Looks like this is ready to land :shipit:

**Pull request merged**
