### PR TITLE
Bump 3.4.0dev1

### PR DESCRIPTION
**Pull request by yakky**

### CODE REVIEW

**Comment by czpython** [comment]
👍

**Comment by yakky** [comment]
@vxsx IDK what I'm doing wrong here https://travis-ci.org/divio/django-cms/jobs/154651788

**Comment by vxsx** [comment]
@yakky also need new css

**Comment by vxsx** [comment]
and actually new fonts

so

```
gulp icons
gulp sass
```

**Comment by yakky** [comment]
@vxsx thanks, done.

**Comment by yakky** [comment]
@vxsx @czpython ok to merge?

**Comment by czpython** [comment]
👍

**Pull request merged**
