### PR TITLE
Prevents login form from redirecting to logout.

### PR DESCRIPTION
**Pull request by jsma**
Refs #3818

### CODE REVIEW

**Comment by yakky** [comment]
is ``logout_url`` a standard context variable?

**Comment by jsma** [comment]
I'm using the "url as" syntax, the actual url name is "logout" which is the Django default.

**Comment by yakky** [comment]
Sorry, I missed the first added line

**Comment by jsma** [comment]
No worries. If there is an alternative preferred approach, let me know.

**Pull request merged**
