### PR TITLE
Fix apphooks clear

### PR DESCRIPTION
**Pull request by yakky**
Maybe :)

### CODE REVIEW

**Comment by yakky** [comment]
@FinalAngel @vxsx  please check if this really fix issues with preview branch

**Comment by vxsx** [comment]
yes please!

**Comment by vxsx** [comment]
looks like it solved the problem

**Comment by yakky** [comment]
@mkoistinen Maybe this part https://github.com/divio/django-cms/pull/4464/files#diff-2a8a0d85dd243bf778b381658688d623R404 can be integrated in apphook_pool.clear() (even if I think only tests will really clear the the apphooks pool)

**Comment by FinalAngel** [comment]
@yakky can we merge to preview (as we would like to create a PR against develop)

**Comment by yakky** [comment]
@FinalAngel waiting for @mkoistinen feedback regarding https://github.com/divio/django-cms/pull/4464#issuecomment-141775102 then I'll merge

**Comment by mkoistinen** [comment]
@yakky I'm afraid I don't understand the comment. =/

**Comment by yakky** [comment]
@mkoistinen I added ``apphook_clear`` method to base test class that deletes ``cms_apps`` modules from ``sys.modules`` before clearing the apphooks list, so that a new discover will still work
This may be a behavior we may want to integrate into ``apphook_pool.clear`` method (https://github.com/divio/django-cms/blob/develop/cms/apphook_pool.py#L19)

**Comment by mkoistinen** [comment]
@yakky, trying it now...

**Comment by mkoistinen** [comment]
OK, I've tried this and it doesn't appear to do any harm. However, it does feel like the "thermonuclear" option. It seems to me we should be fixing register() to work with already-registered apphooks. Having a look at the code, I don't see why it doesn't. What am I missing? Regardless, here's the PR: https://github.com/divio/django-cms/pull/4479

**Comment by yakky** [comment]
@mkoistinen ``discover`` relies on modules loading, which apparently does not work in the same way after jonas changes. The behavior should really only matters in tests, so I'm still undecided whether to incorporate the nuclear option in the ``apphooks_pool``

**Comment by mkoistinen** [comment]
Understood. I'm OK to commit this PR, and disregard #4479. Up to you. I think it is safest to pull this one.

**Comment by yakky** [comment]
@mkoistinen ok, let's play safe for now

**Pull request merged**
