### PR TITLE
Wizard settings

### PR DESCRIPTION
**Pull request by mkoistinen**
Forward ports recent wizard changes to 3.3.x branch. Just cherry-picks the commits, then fixes any merge issues.

### CODE REVIEW

**Comment by czpython** [comment]
Ok to merge

**Comment by mkoistinen** [comment]
Rebased

**Comment by yakky** [comment]
just curious: why not forwardporting 3.2.x branch?

**Comment by mkoistinen** [comment]
@yakky because its error prone.

**Pull request merged**
