### PR TITLE
Fixed #5740 -- Issue when CachedStaticFilesStorage or similar is used

### LINKED ISSUE #5740: The file 'cms/css/cms.base.css' could not be found with CompressedManifestStaticFilesStorage
I am stuck with this issues since yesterday, and cannot find a solution. 

I use django-cookiecutter and integrated my django-cms app. Everything works fine, except when I open pages that have django-cms CSS. I get the following error:

```
ValueError: The file 'cms/css/cms.base.css' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7f238b1fa610>.
  File "django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "opbeat/instrumentation/packages/base.py", line 63, in __call__
    args, kwargs)
  File "opbeat/instrumentation/packages/base.py", line 222, in call_if_sampling
    return self.call(module, method, wrapped, instance, args, kwargs)
  File "opbeat/instrumentation/packages/django/template.py", line 18, in call
    return wrapped(*args, **kwargs)
  File "django/template/base.py", line 208, in render
    return self._render(context)
  File "django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/templatetags/static.py", line 104, in render
    url = self.url(context)
  File "cms/templatetags/cms_static.py", line 31, in url
    url = super(StaticWithVersionNode, self).url(context)
  File "django/templatetags/static.py", line 101, in url
    return self.handle_simple(path)
  File "django/templatetags/static.py", line 114, in handle_simple
    return staticfiles_storage.url(path)
  File "django/contrib/staticfiles/storage.py", line 132, in url
    hashed_name = self.stored_name(clean_name)
  File "django/contrib/staticfiles/storage.py", line 292, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "django/contrib/staticfiles/storage.py", line 95, in hashed_name
    (clean_name, self))
```

Colelctstatic correctly copied the file and whitenoise even `Post-processed` the file:

```
django_1    | Copying '/usr/local/lib/python2.7/site-packages/cms/static/cms/css/3.4.1/cms.base.css'
django_1    | Post-processed 'cms/css/3.4.1/cms.base.css' as 'cms/css/3.4.1/cms.base.1784b3b6c6ab.css'
```

Here are some settings, where I believe they might have an impact:

```
MIDDLEWARE = (
    'django.middleware.security.SecurityMiddleware',
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    # Your stuff goes here (save in config.middlewares)
    'config.middlewares.RequireLoginMiddleware',
)
# STATIC FILE CONFIGURATION
# ------------------------------------------------------------------------------
# See: https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = str(ROOT_DIR('staticfiles'))

# See: https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = '/static/'

# See: https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#std:setting-STATICFILES_DIRS
STATICFILES_DIRS = (
    str(APPS_DIR.path('static')),

)

WHITENOISE_MIDDLEWARE = ('whitenoise.middleware.WhiteNoiseMiddleware', )
MIDDLEWARE = WHITENOISE_MIDDLEWARE + MIDDLEWARE
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
```

Anyone any idea? Any other info you need?

### PR DESCRIPTION
**Pull request by punto1**
fix issue when CachedStaticFilesStorage or similar is used for STATICFILES_STORAGE

for reference: 
steps to reproduce the wrong behaviour:
- install django & django-cms
- in settings.py: 
  *  STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'  
  or STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFilesStorage'
  *  DEBUG = False
- then: python manage.py collectstatic
- python manage runserver 0.0.0.0:8000
-> then visit the page http://<ip_of-your_django_instance>:8000/en/admin/cms/page/
and you will get the error "The file 'cms/css/cms.base.css' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0xb41423cc>."

### Summary

Fixes #

### Links to related discussion
https://github.com/divio/django-cms/issues/5740

### CODE REVIEW

**Comment by czpython** [comment]
Hello @punto1,
Thanks for PR.

Please add an entry to the CHANGELOG.txt file under 3.4.3 with something like "Fixed 404 on static media when using the `CachedStaticFilesStorage` storage or similar."

Also, please rebase your PR with the latest release/3.4.x branch:

```
git rebase release/3.4.x
git push --force
```

**Comment by platzhersh** [comment]
@punto1 @czpython is this save to install from already?

**Comment by czpython** [comment]
@platzhersh Yes I believe this is good to use, tests are failing because of an unrelated issue fixed already on the release/3.4.x branch.

**Comment by punto1** [comment]
Done, apologies for the delay

**Comment by czpython** [comment]
Thanks!
Merged manually in 8fabb5c3ef8b9283b535ea1b76f029c51d3e9c29

**Pull request closed without merging**
