### PR TITLE
Restore previous status of dragbars

### PR DESCRIPTION
**Pull request by astagi**
When clicking on the placeholder title, the opened state of the plugins is toggled

### CODE REVIEW

**Comment by yakky** [comment]
@FinalAngel could you review this?

**Comment by FinalAngel** [comment]
@yakky LGTM

**Comment by yakky** [comment]
@astagi when you have an half-opened placeholder, the first click fully opens all the plugins: is this the desired behavior?

**Comment by astagi** [comment]
@yakky I didn't change the default behaviour, just restored the right status.

**Comment by yakky** [comment]
Thanks @astagi

**Comment by astagi** [comment]
yw

**Pull request merged**
