### PR TITLE
Implement PageTree overhaul

### PR DESCRIPTION
**Pull request by FinalAngel**
This PR fixes numerous issues with the pagetree and slight adaptions. There have been separate pull requests for all code additions already.

image

### CODE REVIEW

**Comment by vxsx** [comment]
looking forward for this :3

**Comment by yakky** [comment]
@FinalAngel @vxsx is this for 3.2?

**Comment by FinalAngel** [comment]
@yakky for 3.2.2

**Comment by yakky** [comment]
I'm not 100% that such a huge refactoring should go in a patch release @divio/django-cms-core 
How about calling next release as 3.3 (released off 3.2.x branch, Imeang)?

**Comment by ojii** [comment]
> I'm not 100% that such a huge refactoring should go in a patch release @divio/django-cms-core 
> How about calling next release as 3.3 (released off 3.2.x branch, Imeang)?

Just looking at the numbers, 250+ commits, 100 changed files, ~8kloc changes I'd say this deserves a version bump, so 3.3 sounds reasonable to me.

**Comment by FinalAngel** [comment]
@ojii it's actually small if you know whats going on. We also had several PR's that lead to this. We actually wanted to merge it to 3.2.0 originally. 3.3.0 will introduce a complete new pagetree design (this only updates jstree to the latest 3.2.1 from originally 0.9 :D

**Pull request merged**
