### PR TITLE
Add icon to toolbar_plugin_struct

### PR DESCRIPTION
**Pull request by ollb**
This is needed for #3765 to work. It add icon to toolbar_plugin_struct so text editor plugins can use it.

### CODE REVIEW

**Comment by ollb** [comment]
Travis lies ;) (the network went wrong during a job).

**Comment by evildmp** [comment]
OK, yes, Travis often lies. Test restarted and passes.

**Comment by mkoistinen** [comment]
@FinalAngel I see this is self-assigned to yourself. What's the status of this?

**Comment by mkoistinen** [comment]
@FinalAngel @yakky is this something that should go into 3.2.4?

**Comment by FinalAngel** [comment]
@mikko-ahlroth-vincit I'd consider it for 3.2.5 TBH, just to be safe. Though I dunno why its still not merged. LGTM form my side

**Comment by yakky** [comment]
Honestly this should go in 3.3 We already added sooo many things to 3.2 branch ... this is a nice API addition, but I'm afraid we would go too far adding this to 3.2

**Comment by FinalAngel** [comment]
@yakky that would also be fine with me, WDYT @mkoistinen

**Pull request closed without merging**
