### PR TITLE
#4771 Adjusted get_object_public_url and get_object_draft_url to use …

### PR DESCRIPTION
**Pull request by marijngoedegebure**
…language attribute.

### CODE REVIEW

**Comment by FinalAngel** [comment]
LGTM

**Comment by yakky** [comment]
@marijngoedegebure it looks good, but I want to check the actual behavior. Moreover, this must be merged on support/3.1 and then forwardported
I'll take care of merging this withing the w-e

**Comment by marijngoedegebure** [comment]
Alright, cool :)

If you need any information on how I stumbled upon this, let me know.

**Comment by yakky** [comment]
@marijngoedegebure I think I got it, but if you can write down the steps to reproduce it would be great (if you can even come up with a test to cover this, it would be super awesome)

**Comment by evildmp** [comment]
@marijngoedegebure Hi, thanks a lot for the report and the patch.

Are you able to write a test case for it?

**Comment by marijngoedegebure** [comment]
I can write down the steps to reproduce tomorrow. I will look at whether I also have time for creating a test case.

**Comment by marijngoedegebure** [comment]
Sorry for the delay, following is a step-by-step procedure to reproduce the error:
1. Setup a basic Django + CMS project (Django version 1.8.X and CMS 3.1.x)
2. Make sure that the project is single language, so no 'django.middleware.locale.LocaleMiddleware' in settings and no i18n_patterns in urls, etc.
3. Run the server, login to the admin interface.
4. Try to view a webpage that includes the cms_toolbar
5. Profit! Oh wait, error!

schermafbeelding 2015-12-03 om 14 53 00

I do not have a lot of experience with writing tests in python for django, so I will need some more time for that.

**Comment by yakky** [comment]
@marijngoedegebure thanks for the information, will check shortly

**Comment by marijngoedegebure** [comment]
Hey @yakky, do you have any idea when 3.1.5 will be released?

**Comment by yakky** [comment]
@marijngoedegebure no ETA: being a bugfix release, as soon as we have a sufficient number of patches merged in (or if some critical issue is fixed, that justify a release itself)
This is a good candidate for a quick 3.1.5 release, for example :)

**Comment by yakky** [comment]
Merged in #4772 
Thanks to @marijngoedegebure for posting this!

**Pull request closed without merging**
