### PR TITLE
Make note about Python3 __str__ instead of __unicode__

### PR DESCRIPTION
**Pull request by k-funk**
In Python 3, `__unicode__` is a non-op: https://docs.djangoproject.com/en/dev/topics/python3/#str-and-unicode-methods

### CODE REVIEW

**Comment by yakky** [comment]
@divio/django-cms-core why not using the ``@python_2_unicode_compatible`` decorator instead?

**Comment by evildmp** [comment]
@k-funk Thanks for this. 

Rather than identifying examples such as this one on a case-by-case basis as we happen to find them, I'd prefer:

* to come up with a clearer, documented process for updating them
* have a concerted effort to identify and fix them right across the documentation.

I'm going to put this on hold while we have a discussion about it and work that out.

**Comment by evildmp** [comment]
@k-funk Please see https://groups.google.com/d/msg/django-cms-developers/S42fLIJ11tI/1bXWDionAQAJ

**Comment by timgraham** [comment]
See https://github.com/django/django/commit/8aa1efff6d6cb1589a1977f3e68f4c26eb6adc74 for Django's docs style.

**Comment by jsma** [comment]
FYI I changed all documentation examples to use `__str__()` in #5444. I missed this conversation before implementing, but this PR can probably be closed.

**Pull request closed without merging**
