### PR TITLE
urlconf during startup: also catch db ProgrammingError

### PR DESCRIPTION
**Pull request by Chive**
The fix introduced in https://github.com/divio/django-cms/pull/4995 only solved my problem half-way, just now I had this error:

```bash
django.db.utils.ProgrammingError: relation "django_site" does not exist
```

### CODE REVIEW

**Comment by Chive** [comment]
Not too sure about the exception I'm catching here. I know for sure that both ``OperationalError`` and ``ProgrammmingError`` happened before. Maybe just catch those two. Or, their base "django.db.utils.DatabaseError"

**Comment by stefanfoulis** [comment]
:+1:

**Comment by yakky** [comment]
@Chive I'd pick ``DatabaseError``: as urlconf maybe loaded when database is not ready in general, I'd go with the superclass for this kind of errors

**Comment by stefanfoulis** [comment]
@yakky ``DatabaseError`` is probably a bit to broad. @Chive looked it up and it seems even a misconfigured field on a Model would be a ``DatabaseError``. If we prevent reporting of that to developers it could be very hard to debug a bug ``models.py``.

**Comment by yakky** [comment]
@stefanfoulis @Chive ok. this is good for merge, then

**Pull request merged**
