### PR TITLE
Fixed a bug when toolbar js is rendered before toolbar (#6270)

### LINKED ISSUE #6270: "ReferenceError: CMS is not defined" when loading a page with the CMS toolbar after upgrading to django-cms 3.5.0
Errors appear in the JavaScript console when loading a page with the CMS toolbar (add ?edit to the URL):

ReferenceError: CMS is not defined bundle.toolbar.min.js:1:389068
ReferenceError: CMS is not defined localhost:8000:10:1   

Sample HTML:
```

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Home</title>
    
<script data-cms src="/static/cms/js/dist/3.5.0/bundle.toolbar.min.js" type="text/javascript"></script>
<script data-cms>
CMS._plugins = CMS._plugins || [];
```
I bisected the change to "Introduced Webpack 3.0 " 1028cf2192856540f9594787f6d8715a914baccf.

### Environment

* Python version: 3.5
* Django version: 1.11.10
* django CMS version: 3.5.0

### PR DESCRIPTION
**Pull request by vxsx**
### Summary

Toolbar javascript expected CMS global to be available by the time script is included. This is sadly not always the case.

Fixes #6270

### Proposed changes in this pull request
Made changes so it would work both ways. Sadly not possible to eliminate extra script tag.

### CODE REVIEW

**Comment by timgraham** [comment]
Confirmed that this fixes the ticket in my report. I can now edit, however, after editing a text plugin and clicking "save", the page seems to display without CSS or something. This is probably a separate issue -- I'll continue debugging.

**Comment by vxsx** [comment]
@timgraham do you have some kind of deferred style loading implemented?

**Comment by timgraham** [comment]
Yes, I'm using Less.js.

**Comment by vxsx** [comment]
@timgraham compiling in client side? 
adding something like this after the toolbar js should help:
```
{% if request.toolbar and request.toolbar.edit_mode_active %}
<script>
CMS.$(window).on('cms-content-refresh', function () {
     less.refresh();
});
</script>
{% endif %}
```

**Comment by vxsx** [comment]
I totally forgot to document that :(

**Comment by timgraham** [comment]
Yes, it works. I opened issue https://github.com/divio/django-cms/issues/6273 to document that. I have `'django.template.context_processors.debug'` activated and started the if statement with `{% if debug ...`. Thanks for your help.

**Pull request merged**
