### PR TITLE
Adds support for `cms copy-site --from X --to X` Issue #3786 

### PR DESCRIPTION
**Pull request by peterfarrell**
Adds a management subcommand to support "cloning" an entire cms site to a new site.

### CODE REVIEW

**Comment by peterfarrell** [comment]
FYI, you must apply PR 3785 in order for this PR to work.

https://github.com/divio/django-cms/pull/3785

**Comment by yakky** [comment]
@peterfarrell thanks for this, I really like it
waiting to merge this after we fix the circular import issue

**Comment by yakky** [comment]
Fix #3786

**Comment by peterfarrell** [comment]
Great, glad you like it! Let me know how you fixed the circular import issue?

**Comment by yakky** [comment]
Documentation (see http://django-cms.readthedocs.org/en/support-3.0.x/reference/cli.html) needed, and at least test for it  (see https://github.com/divio/django-cms/blob/develop/cms/tests/management.py#L318 for reference)

**Comment by yakky** [comment]
subcommands can only use arguments, not options (see https://github.com/divio/django-cms/blob/develop/cms/management/commands/subcommands/copy_lang.py#L27 as example)

**Comment by yakky** [comment]
In #3826 ``Page.copy_page`` has been reworked to allow ``None`` target, please change the command accordingly, as passing a page as first parameter will result in broken tree

**Comment by yakky** [comment]
@peterfarrell #3785 has been merged. could you update this as per comment above?

**Comment by peterfarrell** [comment]
@yakky - definitely, apologies -- I didn't realize that the custom sub-commands don't work like regular commands.

**Comment by yakky** [comment]
No need to apologise, and thanks for spending your time contributing to django CMS

**Comment by yakky** [comment]
@peterfarrell I'd like to merge this in time for 3.1: any ETA for this?

**Pull request closed without merging**
