### PR TITLE
Use "Save as draft"

### PR DESCRIPTION
**Pull request by mkoistinen**
"Save as draft" makes it clearer what is happening than "Save and close". This PR should be complete (including docs, etc.) but leave it open for a few days for review and input from the wider community.

### CODE REVIEW

**Comment by FinalAngel** [comment]
LGTM :+1:

**Comment by yakky** [comment]
:+1:

**Comment by mkoistinen** [comment]
OK, super, can this go into 3.1.1? (note genuine question, its unclear to me if it *should* go there).

**Comment by yakky** [comment]
To me it's minor enough to be entitled in 3.1.1. It's just a wording fix. We should recreate the image for the documentation, though

**Comment by mkoistinen** [comment]
I did already, it's part of this PR :)

**Comment by driesdesmet** [comment]
:+1: With this new wording it's clearer and better than what was there in 3.0.

**Comment by jrief** [comment]
I also prefer the new wording.

**Comment by yakky** [comment]
@mkoistinen oops :D
I'll wait till the sprints to merge it to get more feedback

**Comment by yakky** [comment]
Positive feedback from different sources. Merging this

**Comment by mkoistinen** [comment]
+1

**Pull request merged**
