### PR TITLE
Django CMS Column removed

### PR DESCRIPTION
**Pull request by mebdivio**
## Related resources

* #...
* #...

## Checklist

* [ ] I have opened this pull request against ``develop``
* [ ] I have updated the **CHANGELOG.rst**
* [ ] I have added or modified the tests when changing logic

### CODE REVIEW

**Review by Aiky30 — APPROVED** [review]
There seems to be 2 PR's for this same change, I'm picking the latest to comment on.

I also thought that column was used in the tests but that doesn't appear to be the case, especially as the test suite is passing.

**Comment by Aiky30** [comment]
The branch will need to be brought up to date the latest changes,

**Review by Aiky30 — APPROVED** [review]
Rechecked after the branch was brought up to date.

**Comment by Aiky30** [comment]
@FinalAngel this is fine to be brought in. No changelog entry though,in not sure how you normally manage that, is it at release time or per change?

**Comment by FinalAngel** [comment]
@Aiky30 actually there is a checklist provided when opening a PR, so for this I'll handle it myself but in the future we should be more strict about it.

**Review by FinalAngel — APPROVED** [review]

**Pull request merged**
