### PR TITLE
[WiP] Django 1.9

### PR DESCRIPTION
**Pull request by yakky**
This targets version 3.2

Bigges issues are with third party applications:

* treebeard: 1.9 compatibility not in master or in a released version (only a proposed PR)
* reversion: we need to cleanup a lot our reversion support. 1.9 support in master branch, not in released version

Apparently there are some internal / undocumented changes in 1.9 which cause some test to fail, but I'm not too worried about those

### CODE REVIEW

**Comment by timgraham** [comment]
I think Django 1.9 support could wait until django-cms 3.3. Supporting 4 versions of Django is a bit unwieldy for me. Is there any formal policy about this? Should we discuss it on the mailing list? Past thread about [django-cms LTS? (and Django/Python support policy)](https://groups.google.com/d/topic/django-cms-developers/PH12ZfX4Eeo/discussion) comes to mind. It would be nice to see the discussion happen in public.

**Comment by yakky** [comment]
Will write to ML, the rationale is that 3.3 is a few months away, and the effort to support 1.9 looks small enough to justify adding to it 3.2

**Comment by yakky** [comment]
Comment posted to ML

**Comment by yakky** [comment]
Moving this to merge with 3.2

**Comment by yakky** [comment]
@mkoistinen @FinalAngel @evildmp any opinion on having this on develop or 3.2? Do I need to issue a TB for this?

**Comment by FinalAngel** [comment]
@yakky im in favour of 3.2. Would be nice to add 1.9 support.

**Pull request closed without merging**
