### PR TITLE
Bumped the version number up to release 4.0.0 to avoid confusion with…

### PR DESCRIPTION
**Pull request by Aiky30**
There has been a few cases where developers have been working on the wrong version of the CMS, especially when testing the new app integration features. Please let me know if I need to change anything.

### CODE REVIEW

**Comment by Aiky30** [comment]
@czpython I've made the changes although there seems to be a FE test failing that isn't in the FE list of accepted.

**Comment by Aiky30** [comment]
The gulp build file has the following which would generate a build with the version hardcoded so I'm assuming there is a FE test looking for the version:

glpfile.js:
var CMS_VERSION = fs.readFileSync('cms/__init__.py', { encoding: 'utf-8' }).match(/__version__ = '(.*?)'/)[1];

**Comment by Aiky30** [comment]
I've tried running the FE build and testing myself and it explodes. Haha. What's the CI setup, does it generate the FE build for each commit? Would make sense I guess.

**Comment by czpython** [comment]
Closing this for now

**Pull request closed without merging**
