### PR TITLE
Editorconfig

### PR DESCRIPTION
**Pull request by vxsx**
This PR adds editorconfig as proposed in https://github.com/divio/django-cms/issues/4201

please let me know if there are conventions I missed that should be added to editoconfig

### CODE REVIEW

**Comment by intellectronica** [comment]
:+1: i <3 editorconfig

**Comment by yakky** [comment]
@vxsx :+1:

**Comment by FinalAngel** [comment]
:+1:

**Comment by mkoistinen** [comment]
:+1:

**Comment by FinalAngel** [comment]
@Marketionist @yakky can we merge this?

**Comment by yakky** [comment]
@FinalAngel Done!

**Pull request merged**
