### PR TITLE
[WIP] Better support of custom models

### PR DESCRIPTION
**Pull request by DylannCordel**
We,  [WebU](/webu) (www.webu.coop), are using DjangoCMS and we need some custom model
support improvments. We would be happy if it could be done in DjangoCMS.
Features we ([ollb](/ollb) an [I](/DylannCordel)) would like to develop are explained in issue #2639

### CODE REVIEW

**Comment by FinalAngel** [comment]
Thank you for the contribution @DylannCordel Would you be able to rebase this to the current develop branch?

**Comment by auvipy** [comment]
@DylannCordel whats going on your side about this PR? is everything OK with latest django cms and django framework versions? are you planning to work on it? or looking for someone else for take over?

@FinalAngel is the PR accepted by the technical board?

**Comment by FinalAngel** [comment]
@evildmp @yakky @mkoistinen can you guys evaluate?

**Comment by DylannCordel** [comment]
@auvipy : we (Webu) would like some feedbacks and discussions about "how / what to implement". Unfortunately, we are a small team without a lot of time to work on open source projects and must be sure it won't be thrown to the trash. We would like to work "with you", and not "alone". It is for this reason that we wrote the documentation and few code : to have some feedback about coherence with your future plans for Django-CMS.

**Comment by yakky** [comment]
There a lot of different things going on here and in #2639
And as far as I can see it's a very opinionated way to build custom models (which is not wrong at all per-se, but it might not fit into the CMS core itself)
Most of the code here adds non-existing modules and packages while touch very little the existing core: this suggests me that it's more suitable for an external application that provides hooks and features for other applications to build custom models on top of it, rather than integrating this framework into the core

**Comment by FinalAngel** [comment]
please re-open once the discussion has reached a conclusion in https://github.com/divio/django-cms/issues/2639

**Pull request closed without merging**
