### PR TITLE
Merge #4329

### PR DESCRIPTION
**Pull request by yakky**
Fix #4329

### CODE REVIEW

**Comment by yakky** [comment]
Open for review @mkoistinen @FinalAngel ?

**Comment by mkoistinen** [comment]
LGTM. However, your note above suggests this should be left open until when? The develop branch is the integration branch for 3.3 at this time, so, AFAICT, it should be OK to merge there.

**Comment by yakky** [comment]
Clarified that I meant after **3.2** release and opening of develop for 3.3

**Comment by mkoistinen** [comment]
Develop is already tagged as 3.3.0.dev1.  Should be ok to merge still.

**Comment by yakky** [comment]
@mkoistinen this PR predates 3.2 release, the comment reflects this

**Comment by mkoistinen** [comment]
Understood, but if you leave that comment on, it'll never get merged =)

**Comment by yakky** [comment]
@mkoistinen edited.
My question is: do we need a test for this? I'd say that this is heavily used in our tests, and I've not been able to come up with a clean test case

**Comment by mkoistinen** [comment]
What does coverage say about this PR? I would think that existing tests cover this, at least in spirit.

**Comment by FinalAngel** [comment]
we need also to get into the habit to update the changelog

**Comment by yakky** [comment]
@FinalAngel changelog entry added

**Comment by FinalAngel** [comment]
LGTM

**Pull request merged**
