### PR TITLE
Sync 3.2 with 3.1

### PR DESCRIPTION
**Pull request by yakky**

### CODE REVIEW

**Comment by yakky** [comment]
@mkoistinen @czpython we need to test upgrading a project from 3.1 to tip of 3.1.x branch to this MR as tip 3.1 contains a new migration which I renamed here (and it will need further renaming when moving to develop)
Django 1.8+ seems to behave well, but further testing is very much welcome

**Comment by piotrjakimiak** [comment]
@yakky `./manage.py` has `--merge` option.It doesn't require renaming any migrations.
I've used it many times in my projects and it behave as it should.

Renaming migration will lead to problems with upgrading cms versions.

**Comment by mkoistinen** [comment]
@yakky I used djangocms-installer to create a django1.6.x/cms3.1.x project, created some test content with pages and plugins. Then updated it to the tip of 3.1.x and ran migrations. All seemed fine.

Then, I pip installed 'https://github.com/yakky/django-cms/archive/merge/5078_3.2.zip'. When I did `./manage.py migrate cms` I get this:

```` python
./manage.py migrate cms
Running migrations for cms:
 ! Migration cms:0078_fix_permission_name should not have been applied before cms:0078_auto__add_urlconfrevision but was.
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/mkoistinen/.virtualenvs/tmp/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/mkoistinen/.virtualenvs/tmp/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/mkoistinen/.virtualenvs/tmp/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/mkoistinen/.virtualenvs/tmp/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/mkoistinen/.virtualenvs/tmp/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/Users/mkoistinen/.virtualenvs/tmp/lib/python2.7/site-packages/south/migration/__init__.py", line 214, in migrate_app
    raise exceptions.InconsistentMigrationHistory(problems)
south.exceptions.InconsistentMigrationHistory: Inconsistent migration history
The following options are available:
    --merge: will just attempt the migration ignoring any potential dependency conflicts.
````

I wonder if you addressed the Django migrations, but not the South ones?

**Comment by yakky** [comment]
@mkoistinen I should have addressed both, but apparently not.

**Comment by yakky** [comment]
Closing this in favour of #5186

**Pull request closed without merging**
