### PR TITLE
Add more descriptive __repr__ to Page, Title, Placeholder, and CMSPlugin as well as relevant unit tests

### LINKED ISSUE #5897: nicer __repr__ for Page, Title, CMSPlugin and Placeholder
### Summary

When debugging on the shell or looking at tracebacks it would be very helpful if the default __repr__ for ``Page``, ``Title``, ``CMSPlugin`` and ``Placeholder`` would contain the ``id``

### Expected behaviour

```python
repr(page)
>>> '<cms.models.pagemodel.Page id=12849 object at 0x7fb43e27d590>'
```
or if ``page`` is not saved to the db yet:

```python
repr(page)
>>> '<cms.models.pagemodel.Page id=None object at 0x7fb43e27d590>'
```

#### Actual behaviour

```python
repr(page)
>>> '<cms.models.pagemodel.Page object at 0x7f89c99e9050>'
```

### PR DESCRIPTION
**Pull request by nnja**
### Summary

Fixes #5897

### Links to related discussion

https://github.com/divio/django-cms/issues/5897
cc/ @czpython 

### Proposed changes in this pull request

Add more descriptive __repr__ to Page, Title, Placeholder, and CMSPlugin as well as relevant unit tests

### CODE REVIEW

**Comment by czpython** [comment]
Thanks! :)

**Comment by nnja** [comment]
@czpython one of the test cases failed with the following error message-

`[23:47:21] CasperJS: Resource failed to load` - see the output [here](https://travis-ci.org/divio/django-cms/jobs/235360223)

The message is not very informative. Any thoughts on what might have gone wrong, and how I can troubleshoot?

**Comment by czpython** [comment]
@nnja I've restarted the test. Those failures are usually just timeouts from the node endpoints.

**Comment by czpython** [comment]
One last thing @nnja,
Please add an entry to the CHANGELOG file under 3.5.0.
Like "Introduced customized object repr for ``Page``, ``Title``, ``Placeholder`` and ``CMSPlugin`` models". (with the `` characters)

**Comment by nnja** [comment]
@czpython Entry in CHANGELOG added.

**Pull request merged**
