### PR TITLE
Fixes clipboard not respecting parent restrictions

### LINKED ISSUE #4913: Parent restriction not respected in clipboard
The CMS toolbar does not respect the plugin parent restrictions when the plugin is copied (into the clipboard).

This was first reported in https://github.com/divio/django-cms/pull/4559

- [x] Merge #4914 into 3.2.x
- [x] Forward port to 3.3.x (#4916)

### PR DESCRIPTION
**Pull request by czpython**
* Cleanup toolbar code (reducing queries).
* Reduces queries in clipboard rendering.
* Fixes #4913

### CODE REVIEW

**Comment by vxsx** [comment]
Changelog?

**Comment by czpython** [comment]
@vxsx because not everything has been updated in changelog, I decided to just go through my prs and update changelog individually prior to release.

**Comment by czpython** [comment]
hmm although when I forward port this to 3.3.x would be good to have it there.. ok you win :)

**Comment by czpython** [comment]
As explained by @vxsx [here](https://github.com/divio/django-cms/issues/4913#issuecomment-171589527), frontend tests are not possible before 3.4.

**Comment by mkoistinen** [comment]
LGTM, does this pass manual testing?

**Comment by czpython** [comment]
@mkoistinen yup. will also get @genti94 to test after merge.

**Pull request merged**
