### PR TITLE
Fix error in registering menus

### LINKED ISSUE #3936: CMSAttachMenu failing to register after 3.0.12
I noticed that after upgrading from 3.0.10 to 3.0.12 that a CMSAttachMenu was not registering on a page. It would periodically appear and disappear. In the advanced settings sometimes I would see zero, one, or two options for the same menu. I only have one CMSAttachMenu menu defined in a single app in my project. I attempted to delete and recreate the page to no avail. I noticed in the database, if there was only one option available in advanced settings, the page record showed `UserMenu` for `navigation_extenders`. If there were two options, it would be `UserMenu:190` or `UserMenu:193` depending which option I selected.

Ultimately I reverted to 3.0.10 and the issue went away.

My menu class:

```python
from menus.base import NavigationNode
from cms.menu_bases import CMSAttachMenu
from menus.menu_pool import menu_pool
from django.utils.translation import ugettext_lazy as _

class UserMenu(CMSAttachMenu):

    name = _('User Menu')

    def get_nodes(self, request):
        nodes = []

        menu_id = 1
        root_id = menu_id

        # root node
        greeting = 'Hello, {0}'.format(request.user.get_full_name() or request.user) if request.user.is_authenticated() else 'Log in'
        title = '<i class="fa fa-user hidden-xs hidden-md hidden-lg"></i><span class="hidden-sm">{0}</span>'
        n = NavigationNode(title.format(greeting), "/user/", menu_id)
        nodes.append(n)

        # anonymous menus
        menu_id += 1
        n = NavigationNode(_('Log in'), "/login/", menu_id, root_id, attr={'visible_for_authenticated':False})
        nodes.append(n)

        menu_id += 1
        n = NavigationNode(_('Register'), "/register/", menu_id, root_id, attr={'visible_for_authenticated':False})
        nodes.append(n)

        menu_id += 1
        n = NavigationNode(_('Help'), "/help/ticket/new/guest/", menu_id, root_id, attr={'visible_for_authenticated':False})
        nodes.append(n)

        # authenticated menus
        menu_id += 1
        dashboard_id = menu_id
        n = NavigationNode(_('Dashboard'), "/user/dashboard/", menu_id, root_id, attr={'visible_for_anonymous':False})
        nodes.append(n)

        menu_id += 1
        n = NavigationNode(_('Log out'), "/logout/", menu_id, root_id, attr={'visible_for_anonymous':False})
        nodes.append(n)

        # user section dashboard sub-menu
        menu_id += 1
        n = NavigationNode(_('Dashboard'), "/user/dashboard/", menu_id, dashboard_id, attr={'visible_for_anonymous':False})
        nodes.append(n)

        menu_id += 1
        n = NavigationNode(_('Projects'), "/user/projects/", menu_id, dashboard_id, attr={'visible_for_anonymous':False})
        nodes.append(n)

        menu_id += 1
        n = NavigationNode(_('Help Desk'), "/user/help/", menu_id, dashboard_id, attr={'visible_for_anonymous':False})
        nodes.append(n)

        menu_id += 1
        n = NavigationNode(_('Profile'), "/user/profile/", menu_id, dashboard_id, attr={'visible_for_anonymous':False})
        nodes.append(n)

        return nodes

menu_pool.register_menu(UserMenu)
```

### PR DESCRIPTION
**Pull request by yakky**
Fix #3936

### CODE REVIEW

**Comment by jsma** [comment]
Running a site on an older commit from the develop branch so I manually cherry picked these changes to test on develop locally. On default develop tip, the submenus and breadcrumbs are gone for apphook pages. This patch does not appear to fix the issue. The strange thing is that the custom submenus show up when you're on the CMS page that has the attached apphook, but if you follow a submenu link to an apphook page, the submenu and breadcrumbs disappear. 

Will try to do some debugging tomorrow but I've asked before, are there any upgrade steps for the new apphook config I should be aware of? All I've done is a `git fetch upstream && git merge upstream/develop` and then run the migrations.

**Comment by yakky** [comment]
@jsma no upgrade step is necessary (not even migration). the change is entirely transparent

**Comment by yakky** [comment]
@jsma this should fix it

**Comment by yakky** [comment]
@jsma have you had the chance to recheck after last fix?

**Comment by jsma** [comment]
This appears to fix it, thanks!

**Pull request merged**
