### PR TITLE
Preview Release

### PR DESCRIPTION
**Pull request by FinalAngel**
This merges the current preview efforts mentioned in the [django CMS developers list](https://groups.google.com/forum/#!topic/django-cms-developers/cQEOXWz3rrI) into develop to prepare the first beta release.

This PR contains the following features/fixes:

- Revamped modal design and speedup
- Revamped sideframe design and speedup
- Revamped structureboard design and speedup
- Better drag & drop experience
- Touch support
- Cleanups for toolbar, modal and sideframe
- Cleanups for structureboard and plugins
- Documentation adaptions

### CODE REVIEW

**Comment by yakky** [comment]
Needs #4464 before merge

**Comment by FinalAngel** [comment]
sweet @vxsx also ready from your side?

**Comment by vxsx** [comment]
@FinalAngel will need some time today to make sure tests pass locally (they all do except one, but it's likely messed up environment)

everything else will just likely go on top of develop then

**Comment by vxsx** [comment]
ok apparently it's not messed up environment, trying to figure it out

**Comment by vxsx** [comment]
needs https://github.com/divio/django-cms/pull/4487 in

**Comment by yakky** [comment]
@FinalAngel is the changelog meant to be added later before beta1 release?

**Comment by FinalAngel** [comment]
@yakky yes we track it, we also mention this on the blog post, full changelog will be prepared on rc1.

**Comment by vxsx** [comment]
also needs https://github.com/divio/django-cms/pull/4494 merged

**Pull request merged**
