### PR TITLE
Bugfix spaceless

### PR DESCRIPTION
**Pull request by vxsx**
https://github.com/divio/django-cms/issues/4337

additionally changed html comment to be django comment since it's not necessary to render it

### CODE REVIEW

**Comment by FinalAngel** [comment]
LGTM

**Comment by vxsx** [comment]
will fix tests soon :(

**Comment by FinalAngel** [comment]
@yakky tests pass, ready to be merged :+1:

**Comment by yakky** [comment]
@FinalAngel @vxsx can we fix this in support branches instead (and then forward port it)?

**Comment by vxsx** [comment]
@yakky created PRs for support branches

**Comment by FinalAngel** [comment]
@yakky :+1: all good for merge

**Comment by yakky** [comment]
Fixed in #4467

**Pull request closed without merging**
