### PR TITLE
Fix migration 0010 use of ContentType model

### LINKED ISSUE #5471: Migration 0010 imports ContentType directly
ContentType model should be gotten via get_model (no models should be used directly in data migrations)

### PR DESCRIPTION
**Pull request by doctormo**
Should fix #5471

### CODE REVIEW

**Comment by czpython** [comment]
Thanks! Ok to merge. /cc @mkoistinen @yakky

**Comment by czpython** [comment]
I wonder if we should do the same for the Permission and Group models..

**Comment by doctormo** [comment]
Almost certainly. Do you want a patch?

**Comment by yakky** [comment]
LGTM. This should probably be backported

**Comment by FinalAngel** [comment]
@czpython please merge

**Comment by czpython** [comment]
Thanks. I'll backport to 3.1 and 3.2

**Pull request merged**
