### PR TITLE
Added official Django 1.10 support

### PR DESCRIPTION
**Pull request by yakky**
With the release of treebeard 4.1 we can now support Django 1.10 officially
This PR:
* "promotes" relevant travis matrix items
* Uses official treebeard package
* Change dependency and metadata accordingly
* No code change is required

### CODE REVIEW

**Comment by FinalAngel** [comment]
yay!

**Comment by czpython** [comment]
Thanks @yakky!

**Comment by czpython** [comment]
@yakky I had to adjust this https://github.com/divio/django-cms/commit/76c8129bd3316c91616068f83047716482f4a626 to avoid other PRs from failing.

**Comment by pawelmarkowski** [comment]
@yakky super!

**Comment by jrief** [comment]
Desperately awaiting this version. Especially PR #5781 which currently is a blocker bug for django-SHOP.

**Pull request merged**
