### PR TITLE
Replaces missing migration, fixes up dependencies

### PR DESCRIPTION
**Pull request by mkoistinen**
Also, see #5195 against the 3.2 branch.

### CODE REVIEW

**Comment by czpython** [comment]
I don't agree here, why is the permissions migration not being set as 0015?

**Comment by mkoistinen** [comment]
To maintain the same order as older versions?

**Comment by czpython** [comment]
@mkoistinen this commit https://github.com/divio/django-cms/commit/85cd73b4798898a0b68b3997edaf702e331aa7d7 introduces the migration as 0013 when it should be 0015, once that's changed then here it would match

**Comment by mkoistinen** [comment]
@czpython Good catch. How's this?

**Comment by czpython** [comment]
Ok to merge

**Comment by stefanfoulis** [comment]
👍

**Pull request merged**
