### PR TITLE
set white-space of first column in jstree to normal

### PR DESCRIPTION
**Pull request by jrief**
## Description

If the length of a page title is too long, it pushes the JS-Tree out of the visible window, creating a horizontal scroll bar at the bottom:

Screen Shot 2019-11-19 at 22 47 42

To prevent horizontal scrolling, we can use the proper `white-space: normal` property, so that this text gets wrapped:

Screen Shot 2019-11-19 at 22 46 37
 

## Checklist

* [ ] I have opened this pull request against ``develop``
* [x] I have updated the **CHANGELOG.rst**
* [ ] I have added or modified the tests when changing logic

### CODE REVIEW

**Comment by jrief** [comment]
Rebased for version 3.7.2 and a friendly reminder that some CMS installations really use up to 255 characters for the page title.

**Comment by yakky** [comment]
@jrief could you rebase this against develop? It will be cherrypicked to 3.7.x branch for release. As I'd really like this to be in 3.7.3 which is due soon

BTW: This has been needed for a *long* time! :tada:

**Comment by jrief** [comment]
@yakky ported changes as #6856 to develop branch

**Comment by yakky** [comment]
@jrief :tada: thanks
I'll merge that as the CI will end

**Comment by yakky** [comment]
@FinalAngel should we close this, right? you will port this to 3.7 directly from develop

**Comment by jrief** [comment]
I would keep both PRs separate. Reason is that the css file is compiled and minified, and hence merging presumably impossible.

**Pull request closed without merging**
