### PR TITLE
[WIP] Sane add plugin v2

### PR DESCRIPTION
**Pull request by czpython**
Merging develop into sane add plugin branch.

**Resolved conflicts:**
CONFLICT (content): Merge conflict in manage.py
CONFLICT (content): Merge conflict in .gitignore
CONFLICT (content): Merge conflict in cms/tests/test_menu.py
CONFLICT (content): Merge conflict in cms/tests/test_admin.py
CONFLICT (content): Merge conflict in cms/tests/test_cache.py
CONFLICT (content): Merge conflict in cms/tests/test_permmod.py
CONFLICT (content): Merge conflict in cms/tests/test_plugins.py
CONFLICT (content): Merge conflict in cms/tests/test_no_i18n.py
CONFLICT (content): Merge conflict in cms/tests/test_apphooks.py
CONFLICT (content): Merge conflict in cms/tests/test_security.py
CONFLICT (content): Merge conflict in cms/tests/test_management.py
CONFLICT (content): Merge conflict in cms/admin/placeholderadmin.py
CONFLICT (content): Merge conflict in cms/tests/test_nested_plugins.py
CONFLICT (content): Merge conflict in cms/test_utils/project/nonroot_urls.py
CONFLICT (content): Merge conflict in test_requirements/requirements_base.txt
CONFLICT (content): Merge conflict in cms/static/cms/js/modules/cms.plugins.js
CONFLICT (content): Merge conflict in cms/static/cms/js/dist/bundle.toolbar.min.js

@FinalAngel @vxsx
Please have a look. There's some quite a lot of changes to FE code since this work started.

### CODE REVIEW

**Comment by ojii** [comment]
Just want to say I appreciate you picking this up and wish you good luck. Maybe the tenth time is the charm.

**Comment by czpython** [comment]
Merged develop into sane-add-plugin. Tracked in #4381

**Comment by FinalAngel** [comment]
yeaaaahhhh!

**Comment by ojii** [comment]
this PR is just preparation right? this hasn't landed yet?

**Comment by FinalAngel** [comment]
@ojii it is still in divio/sane-add-plugin just the conflict fixes. Will go through testing first

**Comment by ojii** [comment]
sytmtac

**Comment by FinalAngel** [comment]
image

**Pull request merged**
